'use client'

import { useMemo, useRef, useState } from 'react'
import { MapPin, MessageCircle, Phone, Search, Wrench, Plus } from 'lucide-react'

const categories = ['Todas', 'Borracharia', 'Mecânica', 'Auto Elétrica', 'Mecânica Pesada', 'Guincho / Socorro', 'Lavador de Carreta','Chaveiro'] as const
type CategoryFilter = typeof categories[number]
type Place = { name: string; category: string; city: string; road?: string; phone: string; service?: string }

const places: Place[] = [
  { name: 'GF Mecânica', category: 'Mecânica', city: 'Araguari', phone: '+55 34 99265-6094', service: 'Serviços mecânicos em geral' },
  { name: 'MR Auto Elétrica', category: 'Auto Elétrica', city: 'Araguari', phone: '+55 34 99796-9161', service: 'Socorro elétrico' },
  { name: 'Auto Mecânica Magayver', category: 'Mecânica', city: 'Araguari', phone: '+55 34 99186-6883', service: 'Mecânica geral' },
  { name: 'Auto Mecânica Juninho', category: 'Mecânica', city: 'Araguari', phone: '+55 34 99208-1333', service: 'Manutenção e consertos' },
  { name: 'Mauá Guinchos', category: 'Guincho / Socorro', city: 'Araguari', phone: '+55 34 98810-6577', service: 'Serviço de guincho e reboque' },
  { name: 'Guincho Auto Socorro Baixinho', category: 'Guincho / Socorro', city: 'Araguari', phone: '+55 34 99185-0890', service: 'Auto socorro e reboque' },
  { name: 'Independência Serviço de Guincho', category: 'Guincho / Socorro', city: 'Araguari', phone: '+55 34 98845-0049', service: 'Serviço de guincho 24h' },
  { name: 'Borracharia Móvel Clevin', category: 'Borracharia', city: 'Araguari', phone: '+55 34 99714-8795', service: 'Atendimento móvel de borracharia' },
  { name: 'Borracharia Móvel Araguari Original', category: 'Borracharia', city: 'Araguari', phone: '+55 34 99709-0090', service: 'Socorro de pneus móvel' },
  { name: 'Borracharia do Bryan', category: 'Borracharia', city: 'Araguari', phone: '+55 34 99733-3410', service: 'Conserto de pneus e socorro' },
  { name: 'Borracharia do Ceará', category: 'Borracharia', city: 'Araguari', phone: '+55 34 98825-3999', service: 'Serviços de borracharia' },
  { name: 'Lava Jato de Caminhões BR-050', category: 'Lavador de Carreta', city: 'Araguari', road: 'BR-050', phone: '+55 34 3246-0709', service: 'Lavagem de carretas e caminhões' },
  { name: 'Lava Jato Carrerinha', category: 'Lavador de Carreta', city: 'Araguari', phone: '+55 34 99197-2181', service: 'Lavagem técnica de veículos pesados' },
  { name: 'Machado Lavajato', category: 'Lavador de Carreta', city: 'Araguari', phone: '+55 34 3242-0131', service: 'Lava jato especializado' },
  { name: 'Nunes Borracharia Móvel', category: 'Borracharia', city: 'Uberaba', phone: '+55 34 99630-7576', service: 'Borracharia móvel socorro' },
  { name: 'Borracharia Móvel do Flavim', category: 'Borracharia', city: 'Uberaba', phone: '+55 34 99680-4931', service: 'Atendimento móvel 24h' },
  { name: 'Borracharia Móvel Irmãos Silva', category: 'Borracharia', city: 'Uberaba', phone: '+55 34 99272-5190', service: 'Socorro de pneus para veículos' },
  { name: 'Borracharia do Gil', category: 'Borracharia', city: 'Uberaba', phone: '+55 34 98819-5286', service: 'Conserto e troca de pneus' },
  { name: 'Chaveiro e Borracharia PRIME', category: 'Borracharia', city: 'Uberaba', phone: '+55 34 99637-0669', service: 'Serviço de chaveiro e borracharia' },
  { name: 'Auto Mecânica Chumbrega', category: 'Mecânica', city: 'Uberaba', phone: '+55 34 99105-0053', service: 'Oficina mecânica' },
  { name: 'Auto Elétrica Robinho', category: 'Auto Elétrica', city: 'Uberaba', phone: '+55 34 99196-1502', service: 'Serviços elétricos automotivos' },
  { name: 'M Tec Mecatrônica', category: 'Mecânica', city: 'Uberaba', phone: '+55 34 99912-3020', service: 'Mecatrônica e injeção' },
  { name: 'Mecânica Diesel Ribeiro', category: 'Mecânica Pesada', city: 'Uberaba', phone: '+55 34 99636-8153', service: 'Mecânica diesel pesada' },
  { name: 'JK Auto Socorro', category: 'Guincho / Socorro', city: 'Uberaba', phone: '+55 34 99952-2007', service: 'Guincho e resgate' },
  { name: 'Auto Socorro Danilo', category: 'Guincho / Socorro', city: 'Uberaba', phone: '+55 34 99723-9633', service: 'Socorro e reboque' },
  { name: 'Guincho Equipe Auto Socorro', category: 'Guincho / Socorro', city: 'Uberaba', phone: '+55 34 99888-1746', service: 'Equipe de guincho e suporte' },
  { name: 'Borracharia São João', category: 'Borracharia', city: 'Catalão, GO', phone: '(64) 99627-2006' },
  { name: 'Borracharia Móvel Pit Stop', category: 'Borracharia', city: 'Catalão, GO', phone: '(64) 99934-9057' },
  { name: 'Borracharia Araguaia', category: 'Borracharia', city: 'Catalão, GO', phone: '(64) 99972-5734' },
  { name: 'Borracharia Móvel 050', category: 'Borracharia', city: 'Catalão, GO', road: 'BR-050', phone: '(64) 99286-7163' },
  { name: 'Borracharia do Juninho', category: 'Borracharia', city: 'Catalão, GO', phone: '(64) 99225-3950' },
  { name: 'Borracharia Móvel Odilon', category: 'Borracharia', city: 'Catalão, GO', phone: '(64) 99607-4577' },
  { name: 'Borracharia Móvel do Paulo 24 Horas', category: 'Borracharia', city: 'Catalão, GO', phone: '(64) 98114-0934' },
  { name: 'Borracharia Skinão Loja 01', category: 'Borracharia', city: 'Catalão, GO', phone: '(64) 98409-7360' },
  { name: 'Borracharia do Jairinho', category: 'Borracharia', city: 'Catalão, GO', phone: '(64) 98124-5270' },
  { name: 'Borracharia do Elsinho', category: 'Borracharia', city: 'Catalão, GO', phone: '(64) 99964-8809' },
  { name: 'Borracharia J&S', category: 'Borracharia', city: 'Catalão, GO', phone: '(64) 99986-8444' },
  { name: 'Pit Stop Borrachas e Ferramentas', category: 'Borracharia', city: 'Catalão, GO', phone: '(64) 99922-5835' },
  { name: 'Borracharia e Soldas JK', category: 'Borracharia', city: 'Catalão, GO', phone: '(64) 99695-1006' },
  { name: 'Seu Borracha | Borracharia Móvel Uberlândia', category: 'Borracharia', city: 'Uberlândia, MG', phone: '(34) 99646-8666' },
  { name: 'Borracharia Móvel do Wesley (Veículos em geral)', category: 'Borracharia', city: 'Uberlândia, MG', phone: '(34) 99791-3031' },
  { name: 'Borracharia Móvel 24 Horas GM', category: 'Borracharia', city: 'Uberlândia, MG', phone: '(34) 99245-8786' },
  { name: 'Borracharia Móvel Martins 24 Hrs', category: 'Borracharia', city: 'Uberlândia, MG', phone: '(34) 99140-8254' },
  { name: 'Borracharia Móvel Rapidão (Unidade 1)', category: 'Borracharia', city: 'Uberlândia, MG', phone: '(34) 99874-9766' },
  { name: 'Borracharia Móvel 24h JR', category: 'Borracharia', city: 'Uberlândia, MG', phone: '(34) 99885-1986' },
  { name: 'Borracharia Móvel 24H Sammuel', category: 'Borracharia', city: 'Uberlândia, MG', phone: '(34) 99724-1320' },
  { name: 'Borracharia Móvel Magrão', category: 'Borracharia', city: 'Uberlândia, MG', phone: '(34) 99637-1380' },
  { name: 'Borracharia Móvel do RAFFA', category: 'Borracharia', city: 'Uberlândia, MG', phone: '(34) 99316-4535' },
  { name: 'Borracharia Kometa Móvel', category: 'Borracharia', city: 'Uberlândia, MG', phone: '(34) 98837-4438' },
  { name: 'Euro Car Jardim Guanabara', category: 'Borracharia', city: 'Goiânia, GO', phone: '(62) 98635-9905' },
  { name: 'Curinga dos Pneus', category: 'Borracharia', city: 'Goiânia, GO', phone: '(62) 3291-7090' },
  { name: 'Borracharia do Boca 24 Horas', category: 'Borracharia', city: 'Goiânia, GO', phone: '(62) 3274-2323' },
  { name: 'Borracharia 24 Horas Móvel Dia e Noite', category: 'Borracharia', city: 'Goiânia, GO', phone: '(62) 99331-1571' },
  { name: 'Borracharia J.A. V', category: 'Borracharia', city: 'Goiânia, GO', phone: '(62) 98234-3162' },
  { name: 'Borracharia Pitstop 24HR', category: 'Borracharia', city: 'Goiânia, GO', phone: '(62) 99294-5939' },
  { name: 'Borracharia J.A. III', category: 'Borracharia', city: 'Goiânia, GO', phone: '(62) 98234-3162' },
  { name: '2 Irmãos Auto Elétrica e Mecânica', category: 'Mecânica', city: 'Goiânia, GO', phone: '(62) 99820-8546' },
  { name: 'Mecânica e Elétrica Índio (Socorro 24h Goiânia)', category: 'Mecânica', city: 'Goiânia, GO', phone: '(62) 99863-0815' },
  { name: 'Gel Mecânico 24hs', category: 'Mecânica', city: 'Goiânia, GO', phone: '(62) 98141-4277' },
  { name: 'Auto Mecânica 24 Horas Divair', category: 'Mecânica', city: 'Goiânia, GO', phone: '(62) 98574-2567' },
  { name: 'Auto Elétrica Móvel 24hs (Carro e Caminhões)', category: 'Auto Elétrica', city: 'Goiânia, GO', phone: '(62) 99904-9641' },
  { name: 'Mecânico de Caminhão 24 Horas', category: 'Mecânica Pesada', city: 'Goiânia, GO', phone: '(62) 99929-1447' },
  { name: 'Socorro Mecânico de Embreagem de Caminhão 24 Horas', category: 'Mecânica Pesada', city: 'Goiânia, GO', phone: '(62) 99969-8702' },
  { name: 'Mecânico de Automóveis e Caminhões (Assistência na Estrada 24h)', category: 'Mecânica Pesada', city: 'Goiânia, GO', phone: '(62) 99316-3637' },
  { name: 'Auto Elétrica Porto de Santos', category: 'Auto Elétrica', city: 'Santos - SP', road: 'Av. Conselheiro Nébias, 120', phone: '(13) 3221-1001' },
  { name: 'Borracharia do Valongo', category: 'Borracharia', city: 'Santos - SP', road: 'Rua do Terceiro, 45', phone: '(13) 99712-3456' },
  { name: 'Santos Truck Repair', category: 'Mecânica Pesada', city: 'Santos - SP', road: 'Av. Engenheiro Augusto Barata, s/n', phone: '(13) 3232-4000' },
  { name: 'Lava Rápido e Ducha Carretas Alemoa', category: 'Lavador de Carreta', city: 'Santos - SP', road: 'Marginal da Anchieta, Km 64', phone: '(13) 3296-1500' },
  { name: 'Guincho Litoral 24 Horas', category: 'Guincho / Socorro', city: 'Santos - SP', road: 'Atendimento Anchieta/Imigrantes', phone: '(13) 99123-8899' },
  { name: 'Mecânica Diesel Margem Direita', category: 'Mecânica Pesada', city: 'Santos - SP', road: 'Av. Bandeirantes, 800', phone: '(13) 3219-5500' },
  { name: 'Auto Elétrica e Baterias Alemoa', category: 'Auto Elétrica', city: 'Santos - SP', road: 'Rua Amador Bueno, 310', phone: '(13) 3223-9090' },
  { name: 'Borracharia Ponta da Praia', category: 'Borracharia', city: 'Santos - SP', road: 'Av. Mário Covas, 1500', phone: '(13) 98844-1122' },
  { name: 'Socorro de Pesados Anchieta', category: 'Guincho / Socorro', city: 'Santos - SP', road: 'Rod. Anchieta, Km 60', phone: '(13) 99655-4321' },
  { name: 'Centro Automotivo Cais do Porto', category: 'Mecânica Pesada', city: 'Santos - SP', road: 'Rua Xavier da Silveira, 88', phone: '(13) 3234-1122' },
  { name: 'Elétrica e Eletrônica Diesel Santos', category: 'Auto Elétrica', city: 'Santos - SP', road: 'Av. Martins Fontes, 1020', phone: '(13) 3291-3344' },
  { name: 'Borracharia 24h Saboó', category: 'Borracharia', city: 'Santos - SP', road: 'Av. Marginal Direita, 250', phone: '(13) 99788-6655' },
  { name: 'Borracharia Bahia (Móvel e Fixa - Socorro de Caminhão)', category: 'Borracharia', city: 'São Paulo, SP', phone: '(11) 96854-7941', service: 'Socorro de caminhão / Móvel e Fixa' },
  { name: 'Borracharia Móvel 24h (Socorro de Caminhão)', category: 'Borracharia', city: 'São Paulo, SP', phone: '(11) 98035-7540', service: 'Atendimento 24h / Socorro móvel' },
  { name: 'G2S Borracharia Móvel', category: 'Borracharia', city: 'São Paulo, SP', phone: '(11) 93200-6357', service: 'Borracharia móvel' },
  { name: 'Borracharia Móvel Alyson', category: 'Borracharia', city: 'São Paulo, SP', phone: '(11) 95219-7977', service: 'Atendimento 24h / Móvel' },
  { name: 'Borracharia Móvel Du Gui', category: 'Borracharia', city: 'São Paulo, SP', phone: '(11) 94147-9003', service: 'Socorro 24 Horas' },
  { name: 'Borracharia Negrão Azevedo', category: 'Borracharia', city: 'Ribeirão Preto, SP', phone: '(16) 99103-5393', service: 'Borracharia' },
  { name: 'Borracharia 24 Horas', category: 'Borracharia', city: 'Ribeirão Preto, SP', phone: '(16) 99155-8692', service: 'Atendimento 24h' },
  { name: 'Borracharia do Bruninho', category: 'Borracharia', city: 'Ribeirão Preto, SP', phone: '(16) 99400-1329', service: 'Borracharia' },
  { name: 'IMPAR Borracharia Móvel', category: 'Borracharia', city: 'Ribeirão Preto, SP', phone: '(16) 98199-5756', service: 'Socorro móvel' },
  { name: 'Borracharia Ponto do Pneu', category: 'Borracharia', city: 'Ribeirão Preto, SP', phone: '(16) 99422-7029', service: 'Borracharia' },
  { name: 'JP Borracharia Móvel 24 Horas', category: 'Borracharia', city: 'Araxá, MG', phone: '(34) 99828-6914', service: '24h / Móvel' },
  { name: 'BORRACHARIA MÓVEL EXPRESS', category: 'Borracharia', city: 'Araxá, MG', phone: '(34) 99812-1032', service: 'Móvel' },
  { name: 'Borracharia Móvel e Fixa do Tiago', category: 'Borracharia', city: 'Araxá, MG', phone: '(34) 99817-3240', service: 'Móvel' },
  { name: 'Tiãozinho Borracharia Móvel', category: 'Borracharia', city: 'Araxá, MG', phone: '(34) 99878-2758', service: 'Móvel' },
  { name: 'Borracharia móvel 2 irmãos', category: 'Borracharia', city: 'Araxá, MG', phone: '(34) 99872-6635', service: 'Móvel' },
  { name: 'Borracharia Barreiro', category: 'Borracharia', city: 'Araxá, MG', phone: '(34) 99985-5652' },
  { name: 'Mecânico Araxá MG', category: 'Mecânica', city: 'Araxá, MG', phone: '(34) 99254-1478' },
  { name: 'S.O.S CAMINHONEIRO OFICINA MOVEL', category: 'Mecânica', city: 'Araxá, MG', phone: '(34) 98422-9597', service: 'Móvel / Linha Pesada' },
  { name: 'Tecno Diesel RP Auto Mecânica', category: 'Mecânica Pesada', city: 'Araxá, MG', phone: '(34) 98843-5441', service: 'Linha Pesada' },
  { name: 'Flavio Mecanica Diesel', category: 'Mecânica Pesada', city: 'Araxá, MG', phone: '(34) 98810-5079', service: 'Linha Pesada' },
  { name: 'Sandal Diesel Araxá', category: 'Mecânica Pesada', city: 'Araxá, MG', phone: '(34) 3662-6620', service: 'Linha Pesada' },
  { name: 'PHDiesel araxa', category: 'Mecânica Pesada', city: 'Araxá, MG', phone: '(34) 99231-6669', service: 'Linha Pesada' },
  { name: 'T - Car Diesel', category: 'Mecânica Pesada', city: 'Araxá, MG', phone: '(34) 99773-9133', service: 'Linha Pesada' },
  { name: 'Borracharia Waviva', category: 'Borracharia', city: 'Porto Velho, RO', phone: '(69) 99218-0715', service: 'Porto Velho e Região' },
  { name: 'Borracharia Marechal', category: 'Borracharia', city: 'Porto Velho, RO', phone: '(69) 99987-0725', service: 'Porto Velho e Região' },
  { name: 'Borracharia Pau Ferro', category: 'Borracharia', city: 'Porto Velho, RO', phone: '(69) 99209-7461', service: 'Porto Velho e Região' },
  { name: 'Borracharia do Baixinho', category: 'Borracharia', city: 'Porto Velho, RO', phone: '(69) 99245-1288', service: 'Porto Velho e Região' },
  { name: 'Lácio - Pneus & Borracharia', category: 'Borracharia', city: 'Ariquemes, RO', phone: '(69) 99277-6184' },
  { name: 'Borracharia Móvel Ariquemes', category: 'Borracharia', city: 'Ariquemes, RO', phone: '(69) 99274-0169' },
  { name: 'Borracharia do Goiano', category: 'Borracharia', city: 'Ariquemes, RO', phone: '(69) 98402-9931' },
  { name: 'Borracharia 24 Horas BR-364', category: 'Borracharia', city: 'Ariquemes, RO', road: 'BR-364', phone: '(69) 99314-5582' },
  { name: 'Borracharia Savana (BR-364)', category: 'Borracharia', city: 'Ouro Preto do Oeste, RO', road: 'BR-364', phone: '(69) 99249-8722' },
  { name: 'Borracharia Avenida', category: 'Borracharia', city: 'Ouro Preto do Oeste, RO', phone: '(69) 99283-0274' },
  { name: 'Jiscap OPO (Truck Center)', category: 'Borracharia', city: 'Ouro Preto do Oeste, RO', phone: '(69) 3461-2025', service: 'Truck Center' },
  { name: 'Borracharia do Negão', category: 'Borracharia', city: 'Jaru, RO', phone: '(69) 99285-4120' },
  { name: 'Borracharia Central Jaru', category: 'Borracharia', city: 'Jaru, RO', phone: '(69) 98436-7714' },
  { name: 'Borracharia Santiago', category: 'Borracharia', city: 'Ji-Paraná, RO', phone: '(69) 99255-3489' },
  { name: 'Borracharia Águia', category: 'Borracharia', city: 'Ji-Paraná, RO', phone: '(69) 99351-0208' },
  { name: 'Borracharia Rondônia Pesados', category: 'Borracharia', city: 'Ji-Paraná, RO', phone: '(69) 99911-3040', service: 'Linha Pesada' },
  { name: 'Borracharia Pai e Filha', category: 'Borracharia', city: 'Cacoal, RO', phone: '(69) 99906-3160' },
  { name: 'Borracharia e Auto Center Cacoal', category: 'Borracharia', city: 'Cacoal, RO', phone: '(69) 98418-5022' },
  { name: 'Borracharia Modelo', category: 'Borracharia', city: 'Rolim de Moura, RO', phone: '(69) 98433-6207' },
  { name: 'Borracharia Roda Bem', category: 'Borracharia', city: 'Rolim de Moura, RO', phone: '(69) 99399-9575' },
  { name: 'Rolim Rodas (Pneus Pesados)', category: 'Borracharia', city: 'Rolim de Moura, RO', phone: '(69) 98484-0511', service: 'Pneus Pesados' },
  { name: 'Borracharia Trevo Pesados', category: 'Borracharia', city: 'Pimenta Bueno, RO', phone: '(69) 99201-8843', service: 'Linha Pesada' },
  { name: 'Borracharia do Mineiro', category: 'Borracharia', city: 'Pimenta Bueno, RO', phone: '(69) 98466-1090' },
  { name: 'Borracharia Móvel 24h Belutz', category: 'Borracharia', city: 'Vilhena, RO', phone: '(69) 99256-4762', service: '24h Móvel' },
  { name: 'Borracharia Catarinense', category: 'Borracharia', city: 'Vilhena, RO', phone: '(69) 98455-9243' },
  { name: 'Borracharia A J 24 horas', category: 'Borracharia', city: 'Vilhena, RO', phone: '(69) 99270-5458' },
  { name: 'Borracharia do Pekeno (24h)', category: 'Borracharia', city: 'Guajará-Mirim, RO', phone: '(69) 99345-6731', service: '24h' },
  { name: 'Borracharia Jardim (24h)', category: 'Borracharia', city: 'Guajará-Mirim, RO', phone: '(69) 98458-9809', service: '24h' },
  { name: 'Milla Diesel', category: 'Mecânica Pesada', city: 'Porto Velho, RO', phone: '(69) 98405-4011' },
  { name: 'MaQ & Truck Peças e Serviços', category: 'Mecânica Pesada', city: 'Porto Velho, RO', phone: '(69) 99944-5001' },
  { name: 'Amaral Truck Center', category: 'Mecânica Pesada', city: 'Porto Velho, RO', phone: '(69) 3213-3685' },
  { name: 'Central Diesel Oficina', category: 'Mecânica Pesada', city: 'Porto Velho, RO', phone: '(69) 99926-8925' },
  { name: '364 Mecânica Pesada', category: 'Mecânica Pesada', city: 'Porto Velho, RO', phone: '(69) 99264-7874' },
  { name: 'Mecânica Vargas (Socorro e Pesados)', category: 'Mecânica Pesada', city: 'Ariquemes, RO', phone: '(69) 99282-3551', service: 'Socorro e Pesados' },
  { name: 'Ariquemes Diesel', category: 'Mecânica Pesada', city: 'Ariquemes, RO', phone: '(69) 3535-3022' },
  { name: 'Oficina Mecânica Central Pesados', category: 'Mecânica Pesada', city: 'Ariquemes, RO', phone: '(69) 99311-4045' },
  { name: 'Mecânica Diesel Ouro Preto', category: 'Mecânica Pesada', city: 'Ouro Preto do Oeste, RO', phone: '(69) 99214-7744' },
  { name: 'Vanzin Diesel (Pesados)', category: 'Mecânica Pesada', city: 'Ouro Preto do Oeste, RO', phone: '(69) 3461-3010' },
  { name: 'Mecânica do Baiano (Diesel)', category: 'Mecânica Pesada', city: 'Jaru, RO', phone: '(69) 99341-8012' },
  { name: 'Jaru Eletrodiesel', category: 'Mecânica Pesada', city: 'Jaru, RO', phone: '(69) 3521-2555' },
  { name: 'Central Diesel Truck', category: 'Mecânica Pesada', city: 'Ji-Paraná, RO', phone: '(69) 99235-8594' },
  { name: 'Mecânica JS Diesel', category: 'Mecânica Pesada', city: 'Ji-Paraná, RO', phone: '(69) 99961-4120' },
  { name: 'Rondônia Caminhões', category: 'Mecânica Pesada', city: 'Ji-Paraná, RO', phone: '(69) 3416-9000' },
  { name: 'Cacoal Diesel Pesados', category: 'Mecânica Pesada', city: 'Cacoal, RO', phone: '(69) 3441-4512' },
  { name: 'Mecânica Trevo Caminhões', category: 'Mecânica Pesada', city: 'Cacoal, RO', phone: '(69) 99288-1155' },
  { name: 'Rolim Diesel Mecânica', category: 'Mecânica Pesada', city: 'Rolim de Moura, RO', phone: '(69) 3442-1822' },
  { name: 'Mecânica do Gaúcho (Pesados)', category: 'Mecânica Pesada', city: 'Rolim de Moura, RO', phone: '(69) 99345-5022' },
  { name: 'Pimenta Bueno Diesel', category: 'Mecânica Pesada', city: 'Pimenta Bueno, RO', phone: '(69) 3451-2299' },
  { name: 'Mecânica Rondônia Cargas', category: 'Mecânica Pesada', city: 'Pimenta Bueno, RO', phone: '(69) 99211-6380' },
  { name: 'Tecnodiesel Brasil', category: 'Mecânica Pesada', city: 'Vilhena, RO', phone: '(69) 99230-5429' },
  { name: 'Euro Diesel Especializada', category: 'Mecânica Pesada', city: 'Vilhena, RO', phone: '(69) 98112-8233' },
  { name: 'Rossano Diesel Performance', category: 'Mecânica Pesada', city: 'Vilhena, RO', phone: '(69) 3321-8081' },
  { name: 'Vilhediesel', category: 'Mecânica Pesada', city: 'Vilhena, RO', phone: '(69) 99968-1256' },
  { name: 'Mecânica Diesel Fronteira', category: 'Mecânica Pesada', city: 'Guajará-Mirim, RO', phone: '(69) 98411-9031' },
  { name: 'Oficina do Bigode (Pesados)', category: 'Mecânica Pesada', city: 'Guajará-Mirim, RO', phone: '(69) 99355-1478' },
  { name: 'Borracharia Marechal', category: 'Borracharia', city: 'Porto Velho, RO', phone: '(69) 99987-0725' },
  { name: 'Borracharia Pau Ferro', category: 'Borracharia', city: 'Porto Velho, RO', phone: '(69) 99209-7461' },
  { name: 'Borracharia AJ', category: 'Borracharia', city: 'Vilhena, RO', phone: '(69) 99270-5458' },
  { name: 'Borracharia Belutz', category: 'Borracharia', city: 'Vilhena, RO', phone: '(69) 99256-4762' },
  { name: 'Borracharia Lukinhas', category: 'Borracharia', city: 'Ariquemes, RO', phone: '(69) 99365-2781' },
  { name: 'Borracharia Lukinhas', category: 'Borracharia', city: 'Ariquemes, RO', phone: '(69) 98402-1935' },
  { name: 'Elite Borracharia', category: 'Borracharia', city: 'Betim, MG', phone: '(31) 99850-5946' },
  { name: 'Borracharia M & C', category: 'Borracharia', city: 'Betim, MG', phone: '(31) 97176-3983' },
  { name: 'Borracharia L Castro', category: 'Borracharia', city: 'Betim, MG', phone: '(31) 97583-5479' },
  { name: 'Borracharia Lkb', category: 'Borracharia', city: 'Betim, MG', phone: '(31) 99574-8943' },
  { name: 'Multitrucks', category: 'Mecânica', city: 'Betim, MG', phone: '(31) 99464-7715' },
  { name: 'Multitrucks', category: 'Mecânica', city: 'Betim, MG', phone: '(31) 97574-3409' },
  { name: 'Borracharia Lopes', category: 'Borracharia', city: 'Betim, MG', phone: '(31) 98379-9191' },
  { name: 'GW Pneus Truck Center', category: 'Mecânica', city: 'Betim, MG', phone: '(31) 3593-0885' },
  { name: 'Auto Elétrica do Didi', category: 'Auto Elétrica', city: 'Betim, MG', phone: '(31) 99641-7994' },
  { name: 'RM Mecânica Diesel', category: 'Mecânica', city: 'Betim, MG', phone: '(31) 99245-8025' },
  { name: 'Somar Mecânica Diesel', category: 'Mecânica', city: 'Betim, MG', phone: '(31) 3390-8100' },
  { name: 'Só Iveco Oficina Especializada', category: 'Mecânica', city: 'Betim, MG', phone: '(31) 3532-4444' },
  { name: 'Borracharia Norte Sul', category: 'Borracharia', city: 'Contagem, MG', phone: '(31) 99946-6253' },
  { name: 'Borracharia BH', category: 'Borracharia', city: 'Contagem, MG', phone: '(31) 99785-8878' },
  { name: 'Borracharia Água Branca', category: 'Borracharia', city: 'Contagem, MG', phone: '(31) 98919-6665' },
  { name: 'Borracharia do Balinhas', category: 'Borracharia', city: 'Contagem, MG', phone: '(31) 98430-6006' },
  { name: 'Borracharia Pit Stop', category: 'Borracharia', city: 'Contagem, MG', phone: '(31) 99799-3026' },
  { name: 'Borracharia', category: 'Borracharia', city: 'Contagem, MG', phone: '(31) 97175-0646' },
  { name: 'Borracharia', category: 'Borracharia', city: 'Contagem, MG', phone: '(31) 98725-0490' },
  { name: 'Minasmáquinas Oficina', category: 'Mecânica', city: 'Contagem, MG', phone: '(31) 3514-1160' },
  { name: 'Contagem Diesel Mecânica', category: 'Mecânica', city: 'Contagem, MG', phone: '(31) 3361-2666' },
  { name: 'JVS Mecânica Diesel', category: 'Mecânica', city: 'Contagem, MG', phone: '(31) 99793-1126' },
  { name: '040 Freios', category: 'Mecânica', city: 'Contagem, MG', phone: '(31) 98923-2889' },
  { name: 'Borracharia do Grande', category: 'Borracharia', city: 'Igarapé, MG', phone: '(31) 99834-3048' },
  { name: 'Borracharia Oliveira', category: 'Borracharia', city: 'Juatuba, MG', phone: '(31) 99197-9541' },
  { name: 'Compneus e Borracharia', category: 'Borracharia', city: 'Juatuba, MG', phone: '(31) 97505-0080' },
  { name: 'Borracharia do Leleco', category: 'Borracharia', city: 'Juatuba, MG', phone: '(38) 99975-5279' },
  { name: 'Borracharia Posto Juatuba', category: 'Borracharia', city: 'Juatuba, MG', phone: '(31) 99700-4063' },
  { name: 'Borracharia Manu Pneus', category: 'Borracharia', city: 'São Joaquim de Bicas, MG', phone: '(31) 99613-6928' },
  { name: 'Delo Mecânica e Peças Diesel', category: 'Mecânica', city: 'João Monlevade, MG', phone: '(31) 3852-5022' },
  { name: 'Plantão Diesel', category: 'Mecânica', city: 'João Monlevade, MG', phone: '(31) 99845-6670' },
  { name: 'Mecânica e Borracharia Amigos da 381', category: 'Mecânica', city: 'São Gonçalo do Sapucaí, MG', phone: '(35) 99745-1828' },
  { name: 'Borracharia Martins Pneus', category: 'Borracharia', city: 'Oliveira, MG', phone: '(37) 99813-2313' },
  { name: 'Borracharia do Nado', category: 'Borracharia', city: 'Oliveira, MG', phone: '(37) 99905-5197' },
  { name: 'Borracharia do Adilson', category: 'Borracharia', city: 'Pouso Alegre, MG', phone: '(35) 99872-1813' },
  { name: 'Socorro St. Expedito', category: 'Mecânica', city: 'Pouso Alegre, MG', phone: '(35) 99940-1623' },
  { name: 'Borracharia Pai e Filho', category: 'Borracharia', city: 'Pouso Alegre, MG', phone: '(35) 99849-5591' },
  { name: 'Alvorada Pneus', category: 'Borracharia', city: 'Pouso Alegre, MG', phone: '(35) 3026-4422' },
  { name: 'Borracharia do Cabelo', category: 'Borracharia', city: 'Pouso Alegre, MG', phone: '(35) 99926-4347' },
  { name: 'Borracharia Pais e Filhos', category: 'Borracharia', city: 'Sete Lagoas, MG', phone: '(31) 99829-2543' },
  { name: 'Borracharia Roda7', category: 'Borracharia', city: 'Sete Lagoas, MG', phone: '(31) 99526-3416' },
  { name: 'RJ Borracharia', category: 'Borracharia', city: 'Sete Lagoas, MG', phone: '(31) 99717-8935' },
  { name: 'Borracharia dos Balaios', category: 'Borracharia', city: 'Caetanópolis, MG', phone: '(31) 99986-7502' },
  { name: 'Posto Décio', category: 'Borracharia', city: 'Uberlândia, MG', phone: '(34) 3238-9015' },
  { name: 'Borracharia do Edilson', category: 'Borracharia', city: 'Uberlândia, MG', phone: '(34) 99642-3510' },
  { name: 'Mecânica Uberaba Diesel', category: 'Mecânica', city: 'Uberaba, MG', phone: '(34) 3319-3300' },
  { name: 'Triângulo Diesel', category: 'Mecânica', city: 'Uberaba, MG', phone: '(34) 3311-5060' },
  { name: 'Borracharia do Baiano', category: 'Borracharia', city: 'Uberaba, MG', phone: '(34) 99671-5509' },
  { name: 'Auto Borracharia Triângulo', category: 'Borracharia', city: 'Delta, MG', phone: '(34) 99105-1560' },
  { name: 'Nova Geração Borracharia', category: 'Borracharia', city: 'Barbacena, MG', phone: '(32) 99981-5154' },
  { name: 'Borracharia Pontilhão', category: 'Borracharia', city: 'Barbacena, MG', phone: '(32) 99103-8195' },
  { name: 'Pescoço Pneus e Rodas', category: 'Borracharia', city: 'Barbacena, MG', phone: '(32) 98852-4997' },
  { name: 'Truck Center JF', category: 'Mecânica', city: 'Juiz de Fora, MG', phone: '(32) 3083-6732' },
  { name: 'A Borracharia', category: 'Borracharia', city: 'Juiz de Fora, MG', phone: '(32) 99134-0223' },
  { name: 'Borracharia R6 Zona Norte', category: 'Borracharia', city: 'Juiz de Fora, MG', phone: '(32) 8853-8549' },
  { name: 'Borracharia AJ CAR Vivendas', category: 'Borracharia', city: 'Juiz de Fora, MG', phone: '(32) 98817-3679' },
  { name: 'Borracharia Realeza', category: 'Borracharia', city: 'Manhuaçu, MG', phone: '(33) 99123-5393' },
  { name: 'Borracharia do Neguim', category: 'Borracharia', city: 'Manhuaçu, MG', phone: '(33) 99900-6111' },
  { name: 'Borracharia do Felipe', category: 'Borracharia', city: 'Manhuaçu, MG', phone: '(33) 98415-6185' },
  { name: 'Borracharia São Jorge', category: 'Borracharia', city: 'Manhuaçu, MG', phone: '(33) 99937-3581' },
  { name: 'Mecânica Machado', category: 'Mecânica', city: 'Manhuaçu, MG', phone: '(33) 3331-4090' },
  { name: 'Mecanicar Oficina Diesel', category: 'Mecânica', city: 'Manhuaçu, MG', phone: '(33) 98451-2204' },
  { name: 'Auto Mecânica Diesel Realeza', category: 'Mecânica', city: 'Manhuaçu, MG', phone: '(33) 99195-2015' },
  { name: 'Auto Elétrica Truck Leste', category: 'Auto Elétrica', city: 'Manhuaçu, MG', phone: '(33) 99981-4221' },
  { name: 'Borracharia do Zico', category: 'Borracharia', city: 'Caratinga, MG', phone: '(33) 99947-8761' },
  { name: 'Guinchocar e Socorro', category: 'Mecânica', city: 'Caratinga, MG', phone: '(33) 3321-8161' },
  { name: 'Guinchocar', category: 'Mecânica', city: 'Caratinga, MG', phone: '(33) 99913-3322' },
  { name: 'Pneucar Truck Center', category: 'Mecânica', city: 'Caratinga, MG', phone: '(33) 3329-5555' },
  { name: 'Truck Diesel Mecânica', category: 'Mecânica', city: 'Caratinga, MG', phone: '(33) 99964-5416' },
  { name: 'Caratinga Auto Diesel', category: 'Mecânica', city: 'Caratinga, MG', phone: '(33) 3321-2134' },
  { name: 'Mecânica TL Diesel', category: 'Mecânica', city: 'Caratinga, MG', phone: '(33) 99974-2627' },
  { name: 'Oficina Moreira Diesel', category: 'Mecânica', city: 'Caratinga, MG', phone: '(33) 99731-9630' },
  { name: 'Mecânica Diesel Fernando Pascoal', category: 'Mecânica', city: 'Caratinga, MG', phone: '(33) 99945-8843' },
  { name: 'Matos Diesel Assistência', category: 'Mecânica', city: 'Unaí, MG', phone: '(38) 99997-5637' },
  { name: 'Bap Diesel Motores e Câmbio', category: 'Mecânica', city: 'Unaí, MG', phone: '(38) 3676-2072' },
  { name: 'Borracharia Planalto', category: 'Borracharia', city: 'Unaí, MG', phone: '(38) 3676-1882' },
  { name: 'Mecânica BR Diesel', category: 'Mecânica', city: 'Paracatu, MG', phone: '(38) 3671-5637' },
  { name: 'Borracharia PneuExpress', category: 'Borracharia', city: 'Paracatu, MG', phone: '(38) 99847-5778' },
  { name: 'Borracharia Do Valci', category: 'Borracharia', city: 'Paracatu, MG', phone: '(38) 99977-8252' },
  { name: 'Borracharia do Tavinho', category: 'Borracharia', city: 'Paracatu, MG', phone: '(38) 99955-7178' },
  { name: 'Auto Elétrica e Tacógrafos Paracatu', category: 'Auto Elétrica', city: 'Paracatu, MG', phone: '(38) 3671-3312' },
  { name: 'Montes Claros Diesel', category: 'Mecânica', city: 'Montes Claros, MG', phone: '(38) 2101-7200' },
  { name: 'Mecânica Diesel Norte Sul', category: 'Mecânica', city: 'Montes Claros, MG', phone: '(38) 99912-4022' },
  { name: 'Borracharia Central do Caminhoneiro', category: 'Borracharia', city: 'Montes Claros, MG', phone: '(38) 99144-8899' },
  { name: 'Borracharia do Goiano', category: 'Borracharia', city: 'Bocaiúva, MG', phone: '(38) 99822-1405' },
  { name: 'Borracharia Trevo do Alucinante', category: 'Borracharia', city: 'Engenheiro Navarro, MG', phone: '(38) 99951-6453' },
  { name: 'Posto JK', category: 'Borracharia', city: 'Cristalina, GO', phone: '(61) 3612-1299' },
  { name: 'Borracharia e Truck Center Viana', category: 'Borracharia', city: 'Viana, ES', phone: '(27) 99757-1049' },
  { name: 'Borracharia e Socorro Estrela do Norte', category: 'Borracharia', city: 'Cariacica, ES', phone: '(27) 99849-5591' },
  { name: 'Borracharia do Baiano', category: 'Borracharia', city: 'Cariacica, ES', phone: '(27) 99925-1801' },
  { name: 'Diesel Sul Oficina Mecânica', category: 'Mecânica', city: 'Cariacica, ES', phone: '(27) 3343-1560' },
  { name: 'Borracharia Dois Irmãos', category: 'Borracharia', city: 'Espírito Santo, ES', phone: '(27) 99977-4909' },
  { name: 'Mecânica Valadares', category: 'Mecânica', city: 'Santo Estêvão, BA', phone: '(75) 3245-3273' },
  { name: 'Mecânica Diesel Multimarcas', category: 'Mecânica', city: 'Feira de Santana, BA', phone: '(75) 2101-8400' },
  { name: 'Borracharia Galo Cego', category: 'Borracharia', city: 'Macururé, BA', phone: '(75) 99889-0672' },
  { name: 'Ramon Truck Center & Borracharia', category: 'Borracharia', city: 'Itatim, BA', phone: '(75) 98121-1739' },
  { name: 'Nóbrega Mecânica', category: 'Mecânica', city: 'Guarulhos, SP', phone: '(11) 91334-5378' },
  { name: 'Garage Truck Center', category: 'Mecânica', city: 'São Paulo, SP', phone: '(11) 94772-4954' },
  { name: 'FS Diesel', category: 'Mecânica', city: 'São Paulo, SP', phone: '(11) 94182-3593' },
  { name: 'Borracharia Bahia', category: 'Borracharia', city: 'São Paulo, SP', phone: '(11) 96854-7941' },
  { name: 'Conserta Carros', category: 'Borracharia', city: 'São Paulo, SP', phone: '(11) 4172-0984' },
  { name: 'Borracharia Juracar', category: 'Borracharia', city: 'São Paulo, SP', phone: '(11) 98423-5612' },
  { name: 'Borracharia', category: 'Borracharia', city: 'São Paulo, SP', phone: '(11) 96835-8169' },
  { name: 'Borracharia JK 3 Barras', category: 'Borracharia', city: 'Cristalina, GO', phone: '+55 61 98662-0652' },
  { name: 'Borracharia Triângulo Ipameri', category: 'Borracharia', city: 'Ipameri, GO', phone: '+55 64 99299-2140' },
  { name: 'LIHAN Borracharia Móvel', category: 'Borracharia', city: 'Catalão, GO', phone: '+55 64 98154-8109' },
  { name: 'Borracharia do Baiano', category: 'Borracharia', city: 'Catalão, GO', phone: '+55 64 99961-3430' },
  { name: 'Borracharia e Auto Elétrica do Tião', category: 'Borracharia', city: 'Campo Alegre de Goiás, GO', phone: '+55 64 99654-1102' },
  { name: 'Netinho Pneus Móvel', category: 'Borracharia', city: 'Araguari, MG', phone: '+55 34 98817-5365' },
  { name: 'Borracharia São Cristóvão', category: 'Borracharia', city: 'Uberlândia, MG', phone: '+55 34 3211-1055' },
  { name: 'Borracharia do Geraldo BR-365', category: 'Borracharia', city: 'Uberlândia, MG', phone: '+55 34 98818-5971' },
  { name: 'CT Borracharia Móvel', category: 'Borracharia', city: 'Monte Alegre de Minas, MG', phone: '+55 34 99141-3317' },
  { name: 'Posto Parati Borracharia', category: 'Borracharia', city: 'Patos de Minas, MG', phone: '+55 34 99812-9235' },
  { name: 'Borracharia do Carlão', category: 'Borracharia', city: 'Ibiá, MG', phone: '+55 34 99195-2342' },
  { name: 'Borracharia Móvel Tiãozinho', category: 'Borracharia', city: 'Araxá, MG', phone: '+55 34 98835-1811' },
  { name: 'Borracharia Móvel Juninho Frutal', category: 'Borracharia', city: 'Frutal, MG', phone: '+55 34 99664-1288' },
  { name: 'Borracharia Trevo BR-153', category: 'Borracharia', city: 'Prata, MG', phone: '+55 34 99975-4010' },
  { name: 'Borracharia Chimarrão', category: 'Borracharia', city: 'São José dos Pinhais, PR', phone: '+55 41 99948-0531' },
  { name: 'Borracharia do Polaco', category: 'Borracharia', city: 'Curitiba, PR', phone: '+55 41 98457-7858' },
  { name: 'Borracharia Nogueira', category: 'Borracharia', city: 'Mandirituba, PR', phone: '+55 41 99890-2651' },
  { name: 'Borracharia Móvel Londrina', category: 'Borracharia', city: 'Londrina, PR', phone: '+55 43 98824-6782' },
  { name: 'Borracharia Móvel Socorro', category: 'Borracharia', city: 'Curitiba, PR', phone: '+55 41 99682-7353' },
  { name: 'Guga Borracharia 24h Móvel', category: 'Borracharia', city: 'Criciúma, SC', phone: '+55 48 99108-1696' },
  { name: 'Borracharia Móvel Help Car', category: 'Borracharia', city: 'Itajaí, SC', phone: '+55 47 99134-9471' },
  { name: 'Borracharia Móvel BC', category: 'Borracharia', city: 'Balneário Camboriú, SC', phone: '+55 47 99271-9469' },
  { name: 'JR Porto Borracharia', category: 'Borracharia', city: 'Itajaí, SC', phone: '+55 47 99778-6445' },
  { name: 'Borracharia Palhoça', category: 'Borracharia', city: 'Palhoça, SC', phone: '+55 48 99933-2708' },
  { name: 'Mg Truck Center Linha Pesada', category: 'Mecânica Pesada', city: 'Porto Alegre, RS', phone: '+55 51 3386-6949' },
  { name: 'Lava Jato Truck Car', category: 'Lavador de Carreta', city: 'Catalão, GO', phone: '+55 64 3411-2425' },
  { name: 'DL Lava Jato', category: 'Lavador de Carreta', city: 'Catalão, GO', phone: '+55 64 99222-6529' },
  { name: 'Lava Jato Rota 330', category: 'Lavador de Carreta', city: 'Catalão, GO', phone: '+55 64 99228-7040' },
  { name: 'Lava Jato Mesquita', category: 'Lavador de Carreta', city: 'Catalão, GO', phone: '+55 64 98119-7738' },
  { name: 'Posto de Molas e Lavagem Araguari', category: 'Lavador de Carreta', city: 'Araguari, MG', phone: '+55 34 3242-4509' },
  { name: 'Lava Jato D\'Car Pesados', category: 'Lavador de Carreta', city: 'Rio Grande, RS', phone: '+55 53 3231-5182' },
  { name: 'Auto Elétrica Baterias e Ar Carretão', category: 'Auto Elétrica', city: 'Catalão, GO', phone: '+55 64 3442-6543' },
  { name: 'Auto Elétrica Marajó Pesados', category: 'Auto Elétrica', city: 'Catalão, GO', phone: '+55 64 3441-3022' },
  { name: 'Auto Elétrica Cristal Caminhões', category: 'Auto Elétrica', city: 'Cristalina, GO', phone: '+55 61 3612-5088' },
  { name: 'Auto Elétrica Ipameri Pesados', category: 'Auto Elétrica', city: 'Ipameri, GO', phone: '+55 64 3491-2190' },
  { name: 'Auto Elétrica Triângulo Caminhões', category: 'Auto Elétrica', city: 'Uberlândia, MG', phone: '+55 34 3212-8890' },
  { name: 'Auto Elétrica São Cristóvão Pesados', category: 'Auto Elétrica', city: 'Uberlândia, MG', phone: '+55 34 3231-4055' },
  { name: 'Auto Elétrica e Tacógrafos Uberaba', category: 'Auto Elétrica', city: 'Uberaba, MG', phone: '+55 34 3313-2211' },
  { name: 'Eletrodiesel Zebu Pesados', category: 'Auto Elétrica', city: 'Uberaba, MG', phone: '+55 34 3322-1099' },
  { name: 'Auto Elétrica e Mecânica Pesada Carretão', category: 'Auto Elétrica', city: 'Rio Grande, RS', phone: '+55 53 99122-3040' },
  { name: 'Auto Elétrica Junção Pesados', category: 'Auto Elétrica', city: 'Rio Grande, RS', phone: '+55 53 3232-6022' },
  { name: 'Auto Elétrica do Porto', category: 'Auto Elétrica', city: 'Rio Grande, RS', phone: '+55 53 3235-7711' },
  { name: 'Elétrica Diesel Pelotas', category: 'Auto Elétrica', city: 'Pelotas, RS', phone: '+55 53 3223-9088' },
  { name: 'Clevin Auto Truck Service Elétrica', category: 'Auto Elétrica', city: 'Araguari, MG', phone: '+55 34 99714-8795' },
  { name: 'Ecovias Minas Goiás Guincho', category: 'Guincho / Socorro', city: 'Cristalina, GO', phone: '0800 940 0700' },
  { name: 'Triunfo Concebra Guincho BR-060', category: 'Guincho / Socorro', city: 'Catalão, GO', phone: '0800 060 6000' },
  { name: 'EPR Triângulo Guincho BR-365', category: 'Guincho / Socorro', city: 'Uberlândia, MG', phone: '0800 452 0036' },
  { name: 'Arteris Litoral Sul Guincho Pesado', category: 'Guincho / Socorro', city: 'Curitiba, PR', phone: '0800 725 1771' },
  { name: 'Arteris Planalto Sul Guincho', category: 'Guincho / Socorro', city: 'Curitiba, PR', phone: '0800 717 116' },
  { name: 'CCR ViaCosteira Guincho', category: 'Guincho / Socorro', city: 'Criciúma, SC', phone: '0800 255 5550' },
  { name: 'Chaveiro 24 Horas - Noite e Dia', category: 'Chaveiro', city: 'Catalão, GO', phone: '+55 64 99654-7756', service: 'Abertura de caminhões, chaves codificadas e canivetes 24h' },
  { name: 'Chaveiro Móvel Ágape', category: 'Chaveiro', city: 'Catalão, GO', phone: '+55 64 99284-5014', service: 'Atendimento móvel, abertura automotiva e reparos emergenciais' },
  { name: 'Chaveiro Móvel Novo Mundo Express', category: 'Chaveiro', city: 'Uberlândia, MG', phone: '+55 34 99880-2636', service: 'Socorro veicular 24h, confecção de chaves e troca de segredos' },
  { name: 'Chaveiro Miguel Móvel 24 Horas', category: 'Chaveiro', city: 'Uberlândia, MG', phone: '+55 34 99124-4513', service: 'Atendimento móvel emergencial e resposta imediata' },
  { name: 'AB Center Chaveiro (24 hrs)', category: 'Chaveiro', city: 'Uberaba, MG', phone: '+55 34 98805-1677', service: 'Plantão de abertura de automóveis e cópias gerais 24h' },
  { name: 'Líder Chaveiro (Plantão 24 Horas)', category: 'Chaveiro', city: 'Uberaba, MG', phone: '+55 34 99118-2833', service: 'Atendimento móvel rodoviário e plantão emergencial' },
  { name: 'Alves e Costa Chaveiro 24H', category: 'Chaveiro', city: 'Uberaba, MG', phone: '+55 34 99923-1800', service: 'Abertura de veículos, chaves canivete e codificadas' },
  { name: 'Chaveiro Dis Tranka Pesados', category: 'Chaveiro', city: 'Araguari, MG', phone: '+55 34 99988-0602', service: 'Confecção de chaves codificadas e plantão automotivo' },
  { name: 'Mestre das Chaves 24h', category: 'Chaveiro', city: 'Araguari, MG', phone: '+55 34 99830-3923', service: 'Socorro e abertura rápida de veículos em geral 24h' },
  { name: 'Chaveiro Alvorada 24hs', category: 'Chaveiro', city: 'Rondonópolis, MT', phone: '+55 66 99611-9412', service: 'Controle de alarmes pesados, chaves e atendimento a domicílio' },
  { name: 'Nelsinho Chaveiro 24h', category: 'Chaveiro', city: 'Rondonópolis, MT', phone: '+55 66 99904-2277', service: 'Abertura emergencial e chaveiro profissional de plantão' },
  { name: 'Chaveiro Prime Pesados (Plantão)', category: 'Chaveiro', city: 'Rondonópolis, MT', phone: '+55 66 99617-5411', service: 'Especialista em aberturas de carros e caminhões na BR-364/163' },
  { name: 'Chaveiro 24 Horas - Marcus Chaveiro', category: 'Chaveiro', city: 'Caçapava, SP', phone: '+55 12 99771-8638', service: 'Abertura e confecção de chaves para caminhões na BR-116 Dutra 24h' },
  { name: 'A Solução Chaveiro (Plantão 24h)', category: 'Chaveiro', city: 'Jacareí, SP', phone: '+55 12 97405-9545', service: 'Serviços automotivos e chaves codificadas próximo à Dutra e D. Pedro' },
  { name: 'Chaveiro Guatupê 24 horas', category: 'Chaveiro', city: 'São José dos Pinhais, PR', phone: '+55 41 99664-2016', service: 'Abertura de veículos e cópias de chaves codificadas na BR-376' },
  { name: 'Chaveiro da Félix 24h', category: 'Chaveiro', city: 'Pelotas, RS', phone: '+55 53 98131-6653', service: 'Abertura automotiva e chaves codificadas na BR-116 e BR-392' },
  { name: 'Clínica das Chaves Codificadas 24h', category: 'Chaveiro', city: 'Pelotas, RS', phone: '+55 53 99926-2693', service: 'Socorro e abertura automotiva com veículo de assistência móvel' },
    { name: 'Borracharia Ponto Certo', category: 'Borracharia', city: 'Pires do Rio, GO', phone: '+55 64 99601-0130', service: 'Socorro 24h' },
  { name: 'Borracharia do Henrique', category: 'Borracharia', city: 'Pires do Rio, GO', phone: '+55 64 99658-8608' },
  { name: 'Helpcar Pneus', category: 'Borracharia', city: 'Pires do Rio, GO', phone: '+55 64 99332-3134' },
  { name: 'Auto Center e Mecânica L&F', category: 'Mecânica', city: 'Pires do Rio, GO', phone: '+55 64 3461-2613' },
  { name: 'Auto Mecânica e Elétrica do Irlan', category: 'Auto Elétrica', city: 'Pires do Rio, GO', phone: '+55 64 99227-3096' },
  { name: 'Box 55 Assistência Automotiva', category: 'Mecânica', city: 'Pires do Rio, GO', phone: '+55 64 99901-0775' },
  { name: 'Master Diesel', category: 'Mecânica Pesada', city: 'Pires do Rio, GO', phone: '+55 64 3461-6315', service: 'Bomba e Injeção' },
  { name: 'Pedão Diesel', category: 'Mecânica Pesada', city: 'Pires do Rio, GO', phone: '+55 64 99203-2468', service: 'Especialista em Pickups' },
  { name: 'Oficina do Branco', category: 'Mecânica', city: 'Pires do Rio, GO', phone: '+55 62 98526-4982' },
  { name: 'Auto Elétrica do Luciano', category: 'Auto Elétrica', city: 'Pires do Rio, GO', phone: '+55 64 3015-1040', service: 'Plantão 24h / Agrícola' },
  { name: 'Tennessee Auto Elétrica e Ar Condicionado', category: 'Auto Elétrica', city: 'Pires do Rio, GO', phone: '+55 64 99283-8916' },
  { name: 'Auto Elétrica Luz', category: 'Auto Elétrica', city: 'Pires do Rio, GO', phone: '+55 64 3461-5783' },
  { name: 'CN Borracharia Ambulante Móvel', category: 'Borracharia', city: 'Caldas Novas, GO', phone: '+55 64 99217-1275', service: '24h' },
  { name: 'Marcos Borracharia', category: 'Borracharia', city: 'Caldas Novas, GO', phone: '+55 64 99204-9539', service: '24 horas' },
  { name: 'Auto Center e Borracharia do Claudio', category: 'Borracharia', city: 'Caldas Novas, GO', phone: '+55 64 98414-6380' },
  { name: 'Borracharia Avenida', category: 'Borracharia', city: 'Caldas Novas, GO', phone: '+55 64 99237-6012' },
  { name: 'Borracharia Ambulante Divino Borracheiro', category: 'Borracharia', city: 'Caldas Novas, GO', phone: '+55 64 99206-2862' },
  { name: 'Auto Center e Borracharia do Juliano', category: 'Borracharia', city: 'Caldas Novas, GO', phone: '+55 64 3453-7878' },
  { name: 'Pneus Truck Auto Center', category: 'Borracharia', city: 'Caldas Novas, GO', phone: '+55 64 3455-1028' },
  { name: 'Comando Auto Center', category: 'Mecânica', city: 'Caldas Novas, GO', phone: '+55 64 99207-1136', service: 'Mecânica' },
  { name: 'Felipe Auto Center', category: 'Mecânica', city: 'Caldas Novas, GO', phone: '+55 64 99208-7028', service: 'Mecânica' },
  { name: 'ALA AUTOCAR Mecânica Automotiva', category: 'Mecânica', city: 'Caldas Novas, GO', phone: '+55 64 8458-0003', service: '24h' },
  { name: 'Auto Mecânica Melo e Socorro', category: 'Mecânica', city: 'Caldas Novas, GO', phone: '+55 64 99311-4736', service: '24h' },
  { name: 'SpaceCar Oficina Mecânica', category: 'Mecânica', city: 'Caldas Novas, GO', phone: '+55 64 99297-2809', service: '24h' },
  { name: 'Auto Box Caldas', category: 'Mecânica', city: 'Caldas Novas, GO', phone: '+55 64 3455-4848', service: 'Mecânica' },
  { name: 'Auto Mecânica Laurico', category: 'Mecânica', city: 'Caldas Novas, GO', phone: '+55 64 3454-4820' },
  { name: 'Chaveiro Rei das Chaves e Carimbos', category: 'Chaveiro', city: 'Caldas Novas, GO', phone: '+55 64 99286-3157', service: '24h' },
  { name: 'Chaveiro Nunes', category: 'Chaveiro', city: 'Caldas Novas, GO', phone: '+55 64 99311-3908', service: 'Plantão 24h' },
  { name: 'Chaveiro Médico das Chaves', category: 'Chaveiro', city: 'Caldas Novas, GO', phone: '+55 64 99233-1223', service: '24h / Automotivo' },
  { name: 'Chaveiro Celio Sousa', category: 'Chaveiro', city: 'Caldas Novas, GO', phone: '+55 64 99229-2244', service: 'Plantão 24h' },
  { name: 'Chaveiro Borges', category: 'Chaveiro', city: 'Caldas Novas, GO', phone: '+55 64 99270-0171', service: 'Residencial/Comercial' },
  { name: 'Chaveiro Master Chaves', category: 'Chaveiro', city: 'Caldas Novas, GO', phone: '+55 64 99250-7810' },
  { name: 'Chaveiro Pereira', category: 'Chaveiro', city: 'Caldas Novas, GO', phone: '+55 64 3453-3900', service: 'Chaves Codificadas' },
  { name: 'Premier Auto Elétrica', category: 'Auto Elétrica', city: 'Caldas Novas, GO', phone: '+55 64 99272-3974', service: 'Plantão 24h / Móvel' },
  { name: 'Fast Car Auto Elétrica e Mecânica', category: 'Auto Elétrica', city: 'Caldas Novas, GO', phone: '+55 64 99327-8741', service: '24h' },
  { name: 'Matheus Auto Elétrica', category: 'Auto Elétrica', city: 'Caldas Novas, GO', phone: '+55 64 99284-2021', service: 'Plantão 24h' },
  { name: 'G-Car Auto Elétrica', category: 'Auto Elétrica', city: 'Caldas Novas, GO', phone: '+55 64 99341-7887' },
  { name: 'JP Auto Elétrica Automotiva', category: 'Auto Elétrica', city: 'Caldas Novas, GO', phone: '+55 64 99292-1652' },
  { name: 'Potência Auto Center', category: 'Mecânica', city: 'Caldas Novas, GO', phone: '+55 64 99257-9215' },
  { name: 'GM Borrachas e Ferramentas', category: 'Mecânica', city: 'Ouvidor, GO', phone: '+55 64 99226-2964' },
  { name: 'Marcim Auto Center', category: 'Mecânica', city: 'Ouvidor, GO', phone: '+55 64 98131-3068', service: 'Mecânica' },
  { name: 'ST7 Pneus Centro Automotivo', category: 'Borracharia', city: 'Ouvidor, GO', phone: '+55 64 99907-5531' },
  { name: 'Paraíso Auto Mecânica', category: 'Mecânica', city: 'Ouvidor, GO', phone: '+55 64 99923-0503' },
  { name: 'Auto Elétrica 2001', category: 'Auto Elétrica', city: 'Ouvidor, GO', phone: '+55 64 3478-1293' },
  { name: 'Ultrative Detail', category: 'Mecânica', city: 'Ouvidor, GO', phone: '+55 64 99641-9909', service: 'Estética e Funilaria' },
  { name: 'Chaveiro RP', category: 'Chaveiro', city: 'Ipameri, GO', phone: '+55 64 99253-7282', service: 'Automotivo e Residencial' },
  { name: 'Borracharia Alto do Cruzeiro', category: 'Borracharia', city: 'Ipameri, GO', phone: '+55 64 99251-0202', service: 'Linha Leve' },
  { name: 'Pneus & Borracharia São José Auto Center', category: 'Borracharia', city: 'Ipameri, GO', phone: '+55 64 3491-3466' },
  { name: 'Borracharia São Cristóvão', category: 'Borracharia', city: 'Ipameri, GO', phone: '+55 64 3491-2593' },
  { name: 'Goiás Baterias e Auto Center', category: 'Mecânica', city: 'Ipameri, GO', phone: '+55 64 99303-1049' },
  { name: 'Miguel Eletro Ar', category: 'Auto Elétrica', city: 'Ipameri, GO', phone: '+55 64 99231-9448', service: 'Auto-Elétrica' },
  { name: 'Auto Elétrica São José', category: 'Auto Elétrica', city: 'Ipameri, GO', phone: '+55 64 99245-2138' },
  { name: 'Auto Elétrica Tókio', category: 'Auto Elétrica', city: 'Ipameri, GO', phone: '+55 64 3491-2120' },
  { name: 'Transilva Transporte e Borracharia', category: 'Borracharia', city: 'Corumbaíba, GO', phone: '+55 64 99929-8895', service: 'Móvel' },
  { name: 'Borracharia Móvel Quinca Mariano', category: 'Borracharia', city: 'Corumbaíba, GO', phone: '+55 34 99777-3159' },
  { name: 'Lava Jato e Borracharia Triângulo', category: 'Borracharia', city: 'Corumbaíba, GO', phone: '+55 64 99654-5990' },
  { name: 'Neto Auto Mecânica', category: 'Mecânica', city: 'Corumbaíba, GO', phone: '+55 64 99293-6442' },
  { name: 'S.O.S Borracharia Móvel', category: 'Borracharia', city: 'Campo Alegre de Goiás, GO', phone: '+55 64 99601-1979', service: '24h/Mecânica Diesel' },
  { name: 'Borracharia Paineiras Km 171 BR-050', category: 'Borracharia', city: 'Campo Alegre de Goiás, GO', phone: '+55 64 99654-5727', service: '24h' },
  { name: 'Borracharia do Sissi', category: 'Borracharia', city: 'Campo Alegre de Goiás, GO', phone: '+55 64 99648-8716' },
  { name: 'Chaveiro Sempre Comigo', category: 'Chaveiro', city: 'Catalão, GO', phone: '+55 64 99200-1122', service: 'Automotivo 24h' },
  { name: 'BR Auto Center e Borracharia', category: 'Borracharia', city: 'Catalão, GO', phone: '+55 64 3441-2000', service: 'Loja 1' },
  { name: 'Borracharia Móvel Pit Stop Catanduva', category: 'Borracharia', city: 'Catalão, GO', phone: '+55 64 99604-4512' },
  { name: 'Borracharia Móvel Região', category: 'Borracharia', city: 'Suporte Regional - BR-050', phone: '+55 64 98437-3696' },
  { name: 'Borracharia Móvel Região', category: 'Borracharia', city: 'Suporte Regional - BR-050', phone: '+55 64 98417-6333', service: 'Opção 2' },
  { name: 'Oficina do Tonho', category: 'Mecânica', city: 'Cuiabá, MT', phone: '+55 65 99312-4020', service: 'Mecânica Geral' },
  { name: 'Amortecedores Cuiabá e Mecânica', category: 'Mecânica', city: 'Cuiabá, MT', phone: '+55 65 99238-1154' },
  { name: 'Mecânica Diesel Rodocentro', category: 'Mecânica Pesada', city: 'Cuiabá, MT', phone: '+55 65 3681-4040', service: 'Pesados' },
  { name: 'Auto Center Cuiabá', category: 'Mecânica', city: 'Cuiabá, MT', phone: '+55 65 3624-1020', service: 'Suspensão e Motores' },
  { name: 'Injeção Eletrônica e Mecânica Central', category: 'Mecânica', city: 'Cuiabá, MT', phone: '+55 65 99981-2244' },
  { name: 'Carretão Auto Center', category: 'Mecânica', city: 'Cuiabá, MT', phone: '+55 65 3321-4500', service: 'Mecânica' },
  { name: 'Oficina Mecânica do Mineiro', category: 'Mecânica', city: 'Cuiabá, MT', phone: '+55 65 99602-1188' },
  { name: 'Borracharia 24 Horas', category: 'Borracharia', city: 'Cuiabá, MT', phone: '+55 65 99346-0894', service: 'Av. Miguel Sutil' },
  { name: 'LD Borracharia 24h Cuiabá', category: 'Borracharia', city: 'Cuiabá, MT', phone: '+55 65 99347-7491', service: 'Móvel' },
  { name: 'Borracharia Móvel 24 Horas', category: 'Borracharia', city: 'Cuiabá, MT', phone: '+55 65 99326-0820', service: 'Av. Cel. Escolástico' },
  { name: 'Borracharia do Ceará', category: 'Borracharia', city: 'Cuiabá, MT', phone: '+55 65 99243-5836', service: 'Av. Miguel Sutil - 24h' },
  { name: 'Borracharia Móvel Sousa Pneus', category: 'Borracharia', city: 'Cuiabá, MT', phone: '+55 65 99948-4806' },
  { name: 'Reis da Borracha 24h', category: 'Mecânica', city: 'Cuiabá, MT', phone: '+55 65 99236-8030', service: 'Domiciliar' },
  { name: 'Borracharia Móvel 24 Horas', category: 'Borracharia', city: 'Cuiabá, MT', phone: '+55 65 98125-7964', service: 'Av. Ipiranga' },
  { name: 'Chaveiro Cuiabá 24h', category: 'Chaveiro', city: 'Cuiabá, MT', phone: '+55 65 99244-1188', service: 'Automotivo/Residencial' },
  { name: 'Chaveiro Líder 24 Horas', category: 'Chaveiro', city: 'Cuiabá, MT', phone: '+55 65 99981-4040' },
  { name: 'Real Chaveiro 24h', category: 'Chaveiro', city: 'Cuiabá, MT', phone: '+55 65 99312-3020', service: 'Aberturas e Cópias' },
  { name: 'VG Diesel Oficina Mecânica', category: 'Mecânica Pesada', city: 'Várzea Grande, MT', phone: '+55 65 3685-1550', service: 'Pesados BR-070' },
  { name: 'Centro Automotivo Várzea Grande', category: 'Mecânica', city: 'Várzea Grande, MT', phone: '+55 65 3682-2030' },
  { name: 'Oficina do Gaúcho', category: 'Mecânica', city: 'Várzea Grande, MT', phone: '+55 65 99955-3040', service: 'Mecânica e Suspensão' },
  { name: 'Auto Mecânica Líder', category: 'Mecânica', city: 'Várzea Grande, MT', phone: '+55 65 98402-1133' },
  { name: 'Turbo Diesel Várzea Grande', category: 'Mecânica Pesada', city: 'Várzea Grande, MT', phone: '+55 65 3686-2500', service: 'Injeção' },
  { name: 'Mecânica e Auto Peças Trevo', category: 'Mecânica', city: 'Várzea Grande, MT', phone: '+55 65 3685-1200' },
  { name: 'Borracharia do Gordão VG', category: 'Borracharia', city: 'Várzea Grande, MT', phone: '+55 65 99616-0782', service: 'Centro Sul - 24h' },
  { name: 'Borracharia Top Vip', category: 'Borracharia', city: 'Várzea Grande, MT', phone: '+55 65 8106-1574', service: 'Nova VG - 24h' },
  { name: 'Borracharia do Gordão', category: 'Borracharia', city: 'Várzea Grande, MT', phone: '+55 65 99692-3926', service: 'Chamadas na Madrugada' },
  { name: 'Borracharia Artur Bernardes', category: 'Borracharia', city: 'Várzea Grande, MT', phone: '+55 65 99525-6509', service: '24h' },
  { name: 'Borracharia do Gaúcho', category: 'Borracharia', city: 'Várzea Grande, MT', phone: '+55 65 99611-9338', service: 'Av. Filinto Müller' },
  { name: 'DPE Auto Center e Borracharia', category: 'Borracharia', city: 'Várzea Grande, MT', phone: '+55 65 99251-3379' },
  { name: 'Borracharia & Vulcanizadora Figueiredo', category: 'Borracharia', city: 'Várzea Grande, MT', phone: '+55 65 98171-2579' },
  { name: 'Chaveiro Imperial VG', category: 'Chaveiro', city: 'Várzea Grande, MT', phone: '+55 65 3682-1020' },
  { name: 'Chaveiro Aeroporto 24h', category: 'Chaveiro', city: 'Várzea Grande, MT', phone: '+55 65 99955-4080' },
  { name: 'Borracharia do Gaúcho', category: 'Borracharia', city: 'Confresa, MT', phone: '+55 66 98410-3534', service: 'Plantão 24h' },
  { name: 'Borracharias Modelo', category: 'Borracharia', city: 'Confresa, MT', phone: '+55 66 99969-4570', service: 'Carros e Motos' },
  { name: 'Borracharia e Pneusfresa', category: 'Borracharia', city: 'Confresa, MT', phone: '+55 66 98418-6446' },
  { name: 'Borracharia do Nandinho', category: 'Borracharia', city: 'Confresa, MT', phone: '+55 66 98452-6776' },
  { name: 'Falcão Pneus', category: 'Borracharia', city: 'Confresa, MT', phone: '+55 66 98126-9012', service: 'Leve, Pesada e Agrícola' },
  { name: 'Borracharia 2000', category: 'Borracharia', city: 'Confresa, MT', phone: '+55 66 99717-3936', service: 'Leve e Lavagem' },
  { name: 'Chaveiro Araguaia', category: 'Chaveiro', city: 'Confresa, MT', phone: '+55 66 98410-3500' },
  { name: 'Conserta Car Centro Automotivo', category: 'Mecânica', city: 'Água Boa, MT', phone: '+55 66 98443-7043', service: 'Mecânica' },
  { name: 'Mecanauto Água Boa', category: 'Mecânica Pesada', city: 'Água Boa, MT', phone: '+55 66 99988-4533', service: 'Mecânica Flex/Diesel' },
  { name: 'Marçal Auto Center', category: 'Mecânica', city: 'Água Boa, MT', phone: '+55 66 98115-6621', service: 'Mecânica e Revisão' },
  { name: 'RR Centro Automotivo', category: 'Mecânica', city: 'Água Boa, MT', phone: '+55 66 99983-4150' },
  { name: 'Intercar Centro Automotivo', category: 'Mecânica', city: 'Água Boa, MT', phone: '+55 66 3468-2094' },
  { name: 'Léo Auto Center', category: 'Mecânica', city: 'Água Boa, MT', phone: '+55 66 3468-3024' },
  { name: 'Chaveiro Água Boa', category: 'Chaveiro', city: 'Água Boa, MT', phone: '+55 66 99988-4500' },
  { name: 'Titica - Borracharia, Lava Jato e Vulcanização', category: 'Borracharia', city: 'Canarana, MT', phone: '+55 66 99955-8945' },
  { name: 'Borracharia e Posto de Molas do Zé', category: 'Borracharia', city: 'Canarana, MT', phone: '+55 66 99611-9870' },
  { name: 'Itá Pneus Canarana', category: 'Borracharia', city: 'Canarana, MT', phone: '+55 66 99271-3121' },
  { name: 'Borracharia Araguaia', category: 'Borracharia', city: 'Canarana, MT', phone: '+55 66 99281-1310' },
  { name: 'Borracharia do Gaúcho', category: 'Borracharia', city: 'Sorriso, MT', phone: '+55 66 99654-2180', service: 'BR-163 - 24h' },
  { name: 'Borracharia Brasil', category: 'Borracharia', city: 'Sorriso, MT', phone: '+55 66 3544-7712', service: 'Atendimento Pesado' },
  { name: 'Auto Center e Borracharia Central', category: 'Borracharia', city: 'Sorriso, MT', phone: '+55 66 99988-3314' },
  { name: 'Borracharia KM 743', category: 'Borracharia', city: 'Sorriso, MT', phone: '+55 66 99201-4470', service: 'BR-163' },
  { name: 'Centro Automotivo Sorriso', category: 'Mecânica', city: 'Sorriso, MT', phone: '+55 66 3544-1234', service: 'Mecânica' },
  { name: 'Mecânica Diesel Trevo', category: 'Mecânica Pesada', city: 'Sorriso, MT', phone: '+55 66 99651-8820', service: 'Caminhões' },
  { name: 'Master Car Oficina Mecânica', category: 'Mecânica', city: 'Sorriso, MT', phone: '+55 66 3544-9010' },
  { name: 'Oficina do Mineiro', category: 'Mecânica', city: 'Sorriso, MT', phone: '+55 66 99985-1143', service: 'Mecânica Geral' },
  { name: 'Chaveiro Sorriso 24h', category: 'Chaveiro', city: 'Sorriso, MT', phone: '+55 66 99654-2111' },
  { name: 'Borracharia do Ceará', category: 'Borracharia', city: 'Sinop, MT', phone: '+55 66 99612-8854', service: '24h / Socorro' },
  { name: 'Borracharia Real Pneus', category: 'Borracharia', city: 'Sinop, MT', phone: '+55 66 3531-4040', service: 'Alinhamento' },
  { name: 'Borracharia Dois Irmãos', category: 'Borracharia', city: 'Sinop, MT', phone: '+55 66 99905-1123' },
  { name: 'Auto Borracharia Norte', category: 'Borracharia', city: 'Sinop, MT', phone: '+55 66 3515-6002', service: 'Leve/Pesada' },
  { name: 'Auto Mecânica Sinop', category: 'Mecânica', city: 'Sinop, MT', phone: '+55 66 3531-1550', service: 'Motores/Câmbio' },
  { name: 'Sinop Diesel Mecânica', category: 'Mecânica Pesada', city: 'Sinop, MT', phone: '+55 66 3511-2030', service: 'Linha Pesada' },
  { name: 'Mecânica e Auto Center Carretão', category: 'Mecânica', city: 'Sinop, MT', phone: '+55 66 99602-5541' },
  { name: 'Oficina Mecânica do Baiano', category: 'Mecânica', city: 'Sinop, MT', phone: '+55 66 99981-3090' },
  { name: 'Chaveiro Norte Codificações', category: 'Chaveiro', city: 'Sinop, MT', phone: '+55 66 3531-1500' },
  { name: 'Chaveiro e Alarmes Real', category: 'Chaveiro', city: 'Sinop, MT', phone: '+55 66 99612-8822' },
  { name: 'Borracharia do Baiano', category: 'Borracharia', city: 'Lucas do Rio Verde, MT', phone: '+55 65 99932-1544', service: 'Plantão Móvel' },
  { name: 'Auto Center e Borracharia Rio Verde', category: 'Borracharia', city: 'Lucas do Rio Verde, MT', phone: '+55 65 3549-2280' },
  { name: 'Borracharia Modelo da BR-163', category: 'Borracharia', city: 'Lucas do Rio Verde, MT', phone: '+55 65 99611-3090' },
  { name: 'Oficina Mecânica Lucas', category: 'Mecânica', city: 'Lucas do Rio Verde, MT', phone: '+55 65 3549-1122', service: 'Injeção/Motor' },
  { name: 'LR Diesel e Mecânica', category: 'Mecânica Pesada', city: 'Lucas do Rio Verde, MT', phone: '+55 65 99964-1515', service: 'Pesados' },
  { name: 'Centro Automotivo Rio Verde', category: 'Mecânica', city: 'Lucas do Rio Verde, MT', phone: '+55 65 3549-3380' },
  { name: 'Chaveiro Rio Verde', category: 'Chaveiro', city: 'Lucas do Rio Verde, MT', phone: '+55 65 99932-1515' },
  { name: 'Borracharia do Goiano', category: 'Borracharia', city: 'Nova Mutum, MT', phone: '+55 65 99688-4120', service: 'Socorro 24h' },
  { name: 'Truck Pneus e Borracharia', category: 'Borracharia', city: 'Nova Mutum, MT', phone: '+55 65 3408-1515', service: 'Caminhões' },
  { name: 'Borracharia Mutum', category: 'Borracharia', city: 'Nova Mutum, MT', phone: '+55 65 99952-1188' },
  { name: 'Mecânica Mutum', category: 'Mecânica', city: 'Nova Mutum, MT', phone: '+55 65 3408-1020', service: 'Revisão Geral' },
  { name: 'Top Car Centro Automotivo', category: 'Mecânica', city: 'Nova Mutum, MT', phone: '+55 65 99672-4411' },
  { name: 'Mutum Diesel Oficina Mecânica', category: 'Mecânica Pesada', city: 'Nova Mutum, MT', phone: '+55 65 3408-2290' },
  { name: 'Chaveiro Mutum', category: 'Chaveiro', city: 'Nova Mutum, MT', phone: '+55 65 3408-1010' },
  { name: 'Tecnocar Auto Mecânica', category: 'Mecânica', city: 'Rondonópolis, MT', phone: '+55 66 3421-9838', service: 'Leve/Geral' },
  { name: 'FERCAR Oficina Mecânica', category: 'Mecânica', city: 'Rondonópolis, MT', phone: '+55 66 99999-4774' },
  { name: 'Oficina.com', category: 'Mecânica', city: 'Rondonópolis, MT', phone: '+55 66 99717-6666', service: 'Centro Automotivo' },
  { name: 'Telmocar', category: 'Mecânica', city: 'Rondonópolis, MT', phone: '+55 66 3426-7688', service: 'Especialista Caminhonetes' },
  { name: 'Nax Service Diesel', category: 'Mecânica Pesada', city: 'Rondonópolis, MT', phone: '+55 66 99955-5640', service: 'Oficina Móvel' },
  { name: 'Paraná Diesel', category: 'Mecânica Pesada', city: 'Rondonópolis, MT', phone: '+55 66 99663-2345', service: 'Linha Mercedes Benz' },
  { name: 'Mecânica Diesel Leomar', category: 'Mecânica Pesada', city: 'Rondonópolis, MT', phone: '+55 66 99935-4073' },
  { name: 'Chaveiro Central 24h', category: 'Chaveiro', city: 'Rondonópolis, MT', phone: '+55 66 99999-4700' },
  { name: 'Muniz Auto Center Primavera', category: 'Mecânica', city: 'Primavera do Leste, MT', phone: '+55 66 99620-6925' },
  { name: 'Riata Auto Mecânica', category: 'Mecânica', city: 'Primavera do Leste, MT', phone: '+55 66 99615-9408' },
  { name: 'JUNIOR AUTO CENTER', category: 'Mecânica', city: 'Primavera do Leste, MT', phone: '+55 66 99998-8027' },
  { name: 'Pva Diesel Bombas Injetoras', category: 'Mecânica Pesada', city: 'Primavera do Leste, MT', phone: '+55 66 99216-7871' },
  { name: 'Rigatti Diesel', category: 'Mecânica Pesada', city: 'Primavera do Leste, MT', phone: '+55 66 3498-7172', service: 'Linha Pesada' },
  { name: 'AUTO MOLAS TH DIESEL', category: 'Mecânica Pesada', city: 'Primavera do Leste, MT', phone: '+55 66 99650-7353', service: 'Suspensão' },
  { name: 'Chaveiro Automotivo Pva', category: 'Chaveiro', city: 'Primavera do Leste, MT', phone: '+55 66 99620-6900' },
  { name: 'M.E Pneus e Borracharia', category: 'Borracharia', city: 'Nova Xavantina, MT', phone: '+55 66 98102-0849', service: 'Nova Xavantina' },
  { name: 'Amigão Pneus', category: 'Borracharia', city: 'Nova Xavantina, MT', phone: '+55 66 3438-1632', service: 'Nova Xavantina' },
  { name: 'Auto Center Prime', category: 'Mecânica', city: 'Nova Xavantina, MT', phone: '+55 66 3438-2321', service: 'Nova Xavantina' },
  { name: 'Borracharia Meta', category: 'Borracharia', city: 'Vila Rica, MT', phone: '+55 66 98402-3652', service: 'Vila Rica' },
  { name: 'Borracharia e Auto Center Araguaia', category: 'Borracharia', city: 'Vila Rica, MT', phone: '+55 66 3554-1211', service: 'Vila Rica' },
  { name: 'Mecânica e Auto Peças Trevo', category: 'Mecânica', city: 'Vila Rica, MT', phone: '+55 66 3554-1500', service: 'Vila Rica' },
  { name: 'Borracharia Móvel do Cabelo', category: 'Borracharia', city: 'Rio Branco, AC', phone: '+55 68 99256-1499', service: '24h' },
  { name: 'Borracharia 607', category: 'Borracharia', city: 'Rio Branco, AC', phone: '+55 68 99911-7209', service: 'Aberto até as 23h' },
  { name: 'Borracharia Messias', category: 'Borracharia', city: 'Rio Branco, AC', phone: '+55 68 99602-9309', service: 'Consertos' },
  { name: 'Alan Auto Mecânica', category: 'Mecânica', city: 'Rio Branco, AC', phone: '+55 68 99913-3266', service: 'Geral/Suspensão' },
  { name: 'Auto Mecânica Carvalho', category: 'Mecânica Pesada', city: 'Rio Branco, AC', phone: '+55 68 99974-4580', service: 'Diesel Pesada' },
  { name: 'Welyngton Chaveiro Automotivo', category: 'Chaveiro', city: 'Rio Branco, AC', phone: '+55 68 99969-3327', service: '24h' },
  { name: 'Alex Chaveiro', category: 'Chaveiro', city: 'Rio Branco, AC', phone: '+55 68 99932-0777', service: 'Chaves Codificadas' },
  { name: 'Lando Chaveiro', category: 'Chaveiro', city: 'Rio Branco, AC', phone: '+55 68 99987-5942', service: 'Abertura e Resgate' },
  { name: 'Borracharia do Goiano', category: 'Borracharia', city: 'Cruzeiro do Sul, AC', phone: '+55 68 99933-2144', service: 'Plantão' },
  { name: 'Oficina Mecânica Juruá Diesel', category: 'Mecânica Pesada', city: 'Cruzeiro do Sul, AC', phone: '+55 68 3322-1500', service: 'Caminhões' },
  { name: 'Gold Cópias Chaves e Carimbos', category: 'Mecânica', city: 'Cruzeiro do Sul, AC', phone: '+55 68 99948-8346', service: 'Emergências 24h' },
  { name: 'Fabricópias', category: 'Mecânica', city: 'Cruzeiro do Sul, AC', phone: '+55 68 99914-4000', service: 'Chaves Codificadas' },
  { name: 'Borracharia Costa', category: 'Borracharia', city: 'Sena Madureira, AC', phone: '+55 68 99968-4669', service: 'Socorro e Vulcanização' },
  { name: 'Borracharia e Auto Peças Junior', category: 'Borracharia', city: 'Sena Madureira, AC', phone: '+55 68 99973-7508' },
  { name: 'Oficina e Auto Peças Sena', category: 'Mecânica', city: 'Sena Madureira, AC', phone: '+55 68 3371-1200', service: 'Mecânica' },
  { name: 'S.O.S PNEUS', category: 'Borracharia', city: 'Brasiléia, AC', phone: '+55 68 99962-2249', service: 'Guincho e Borracharia' },
  { name: 'Borracharia Trevo', category: 'Borracharia', city: 'Brasiléia, AC', phone: '+55 68 99211-2458', service: 'Aberto até as 22h' },
  { name: 'Lubri Pneus Brasiléia', category: 'Borracharia', city: 'Brasiléia, AC', phone: '+55 68 3546-3023', service: 'Centro Automotivo' },
  { name: 'Lubri Pneus Celular', category: 'Borracharia', city: 'Brasiléia, AC', phone: '+55 68 99254-7927', service: 'Mecânica/Pneus' },
  { name: 'Borracharia e Oficina RM', category: 'Borracharia', city: 'Tarauacá, AC', phone: '+55 68 99973-7636', service: 'Na Rodovia' },
  { name: 'Oficina do Frota', category: 'Mecânica', city: 'Tarauacá, AC', phone: '+55 68 99223-2364', service: 'Mecânica e Motores' },
  { name: 'Oficina do Pequeno', category: 'Mecânica', city: 'Tarauacá, AC', phone: '+55 68 99218-1581' },
  { name: 'Borracharia João de Deus', category: 'Borracharia', city: 'Feijó, AC', phone: '+55 68 99913-7821' },
  { name: 'Oficina do Van', category: 'Mecânica', city: 'Feijó, AC', phone: '+55 68 99961-1951', service: 'Mecânica Geral' },
  { name: 'Oficina Chico Ferro', category: 'Mecânica', city: 'Feijó, AC', phone: '+55 68 99963-3893', service: 'Mecânica' },
  { name: 'BL Auto Peças', category: 'Mecânica', city: 'Feijó, AC', phone: '+55 68 99235-3541', service: 'Suporte e Reposição' },
  { name: 'Borracharia Mariano', category: 'Borracharia', city: 'Humaitá, AM', phone: '+55 97 98403-8204', service: 'Transamazônica' },
  { name: 'JC Moto Peças e Borracharia', category: 'Borracharia', city: 'Humaitá, AM', phone: '+55 97 98452-9270' },
  { name: 'Auto Peças e Mecânica Wagner e Jalles', category: 'Mecânica', city: 'Goiandira, GO', phone: '+55 64 3462-1218' },
  { name: 'Lava Jato e Borracharia Ribeiro', category: 'Borracharia', city: 'Nova Aurora, GO', phone: '+55 64 3698-1050' },
{ nome: "Lava Jato e Transportadora Carrerinha", cidade: "Araguari - MG", categoria: "lava-jato", whatsapp: "34992381184" },
{ nome: "Lava Jato Truck Car", cidade: "Uberlândia - MG", categoria: "lava-jato", whatsapp: "34996428821" },
{ nome: "Lava Jato de Caminhão Lave Truck", cidade: "Uberlândia - MG", categoria: "lava-jato", whatsapp: "34998230512" },
{ nome: "Lava Jato Almeida", cidade: "Uberlândia - MG", categoria: "lava-jato", whatsapp: "34999925800" },
{ nome: "Lava Jato Família", cidade: "Uberlândia - MG", categoria: "lava-jato", whatsapp: "34996451347" },
{ nome: "Jato Caminhões", cidade: "Uberlândia - MG", categoria: "lava-jato", whatsapp: "34920601068" },
{ nome: "Lava Jato Aliança - Fixo", cidade: "Uberaba - MG", categoria: "lava-jato", whatsapp: "3433385607" },
{ nome: "Lava Jato Aliança - WhatsApp", cidade: "Uberaba - MG", categoria: "lava-jato", whatsapp: "34998770821" },
{ nome: "Lava Jato Irmãos Coimbra", cidade: "Uberaba - MG", categoria: "lava-jato", whatsapp: "34996434166" },
{ nome: "Lava Jato do Auto Posto Jaó", cidade: "Frutal - MG", categoria: "lava-jato", whatsapp: "3434235856" },
{ nome: "Crystal Car Estética Pesada", cidade: "Cristalina - GO", categoria: "lava-jato", whatsapp: "61998295503" },
{ nome: "Dadinho Truck Center & Lava Jato", cidade: "Goiânia - GO", categoria: "lava-jato", whatsapp: "6230937010" },
{ nome: "Lava Rápido Fonte Água Viva", cidade: "Goiânia - GO", categoria: "lava-jato", whatsapp: "62984770770" },
{ nome: "Box7go Estética e Lava Jato", cidade: "Goiânia - GO", categoria: "lava-jato", whatsapp: "62982416008" },
{ nome: "JE Lava Jato Linha Leve/Pesada", cidade: "São José do Rio Preto - SP", categoria: "lava-jato", whatsapp: "17997442754" },
{ nome: "Lava Jato Oriental", cidade: "São José do Rio Preto - SP", categoria: "lava-jato", whatsapp: "1730127789" },
{ nome: "LavaX Jato Automotivo", cidade: "Taguatinga - DF", categoria: "lava-jato", whatsapp: "61996521685" },
{ nome: "Lava Jato Sucesso", cidade: "Taguatinga - DF", categoria: "lava-jato", whatsapp: "61985394599" },
{ nome: "Fernandes Truck Lava Jato", cidade: "Sumaré - SP", categoria: "lava-jato", whatsapp: "19987709642" },
{ nome: "Ameritanques Descontaminação", cidade: "Americana - SP", categoria: "lava-jato", whatsapp: "19983080086" },
{ nome: "Lavador Limpar Bem", cidade: "Cordeirópolis - SP", categoria: "lava-jato", whatsapp: "19996485221" },
{ nome: "Lava Car Everton", cidade: "Monte Alto - SP", categoria: "lava-jato", whatsapp: "16997109076" },
{ nome: "Mauro Lavador de Caminhão", cidade: "São Carlos - SP", categoria: "lava-jato", whatsapp: "16994047250" },
{ nome: "Lavador Alegria", cidade: "Barretos - SP", categoria: "lava-jato", whatsapp: "17991154424" },
{ nome: "Lava Truck Osasco", cidade: "Osasco - SP", categoria: "lava-jato", whatsapp: "11963149468" },
{ nome: "Star Truck da Érica", cidade: "Osasco - SP", categoria: "lava-jato", whatsapp: "11952215689" },
{ nome: "Lava Rápido Pajeú", cidade: "Osasco - SP", categoria: "lava-jato", whatsapp: "11917240761" },
{ nome: "Lava Bem Caminhões", cidade: "São Paulo - SP", categoria: "lava-jato", whatsapp: "1129556500" },
{ nome: "Lava Jato Rondonópolis Prime", cidade: "Rondonópolis - MT", categoria: "lava-jato", whatsapp: "66996514040" },
{ nome: "Lavador Jato Forte", cidade: "Rondonópolis - MT", categoria: "lava-jato", whatsapp: "66999128815" },
{ nome: "Truck Center e Lavagem Pesada Dourados", cidade: "Dourados - MS", categoria: "lava-jato", whatsapp: "6734244001" },
{ nome: "Lava Jato Pesados Ituiutaba", cidade: "Ituiutaba - MG", categoria: "lava-jato", whatsapp: "3432681500" },
{ nome: "Lavador de Caminhões do Posto Trevo", cidade: "Patos de Minas - MG", categoria: "lava-jato", whatsapp: "3438221200" },
{ nome: "Lava Jato Diesel Patrocínio", cidade: "Patrocínio - MG", categoria: "lava-jato", whatsapp: "34991448020" },
{ nome: "Carrara Lava Jato de Caminhões", cidade: "Maringá - PR", categoria: "lava-jato", whatsapp: "4430291815" },
{ nome: "Carrara Caminhões - WhatsApp", cidade: "Maringá - PR", categoria: "lava-jato", whatsapp: "44984399311" },
{ nome: "Lava Jato do Posto Quinta", cidade: "Campo Largo - PR", categoria: "lava-jato", whatsapp: "4133921144" },
{ nome: "Lava Jato de Caminhão Garagem do Bruto", cidade: "Simões Filho - BA", categoria: "lava-jato", whatsapp: "71993496883" },
{ nome: "Gomes Lava Car Linha Pesada", cidade: "Jacobina - BA", categoria: "lava-jato", whatsapp: "74981334409" },
{ nome: "Lava Jato Só Pesados", cidade: "Araguaína - TO", categoria: "lava-jato", whatsapp: "6334143870" },
{ nome: "Pit Stop Lava Jato de Caminhão", cidade: "Araguaína - TO", categoria: "lava-jato", whatsapp: "63992455512" },
{ nome: "Lava Jato Brilho Car Linha Pesada", cidade: "Gurupi - TO", categoria: "lava-jato", whatsapp: "63999872699" },
{ nome: "Borracharia Móvel O Marreta", cidade: "Fortaleza - CE", categoria: "borracharia", whatsapp: "85997304384" },
{ nome: "Borracharia Móvel 24 horas Ce", cidade: "Fortaleza - CE", categoria: "borracharia", whatsapp: "85920030491" },
{ nome: "Borracharia pai & filho", cidade: "Fortaleza - CE", categoria: "borracharia", whatsapp: "85984064047" },
{ nome: "Borracharia 24 Horas Gabriel", cidade: "Fortaleza - CE", categoria: "borracharia", whatsapp: "85987632692" },
{ nome: "Borracharia Santo Antônio", cidade: "Fortaleza - CE", categoria: "borracharia", whatsapp: "85922788322" },
{ nome: "Borracharia 24h - Joaquim Távora", cidade: "Fortaleza - CE", categoria: "borracharia", whatsapp: "8532575300" },
{ nome: "WVA Borracharia 24 Horas", cidade: "Fortaleza - CE", categoria: "borracharia", whatsapp: "85986780042" },
{ nome: "Borracharia Top - Messejana", cidade: "Fortaleza - CE", categoria: "borracharia", whatsapp: "85986191727" },
{ nome: "Lojão do Borracheiro", cidade: "Fortaleza - CE", categoria: "borracharia", whatsapp: "85987146729" },
{ nome: "Borracharia Pai e Filhos - BR-116", cidade: "Jaguaribe - CE", categoria: "borracharia", whatsapp: "88996701001" },
{ nome: "Borracharia Móvel JJ", cidade: "Jaguaribe - CE", categoria: "borracharia", whatsapp: "88998008159" },
{ nome: "Borracharia 24 Horas - BR-101 Sul", cidade: "Recife - PE", categoria: "borracharia", whatsapp: "81992168399" },
{ nome: "Borracheiro PE - Vulcanização e Linha Pesada", cidade: "Igarassu - PE", categoria: "borracharia", whatsapp: "81989030408" },
{ nome: "Léo Borracharia", cidade: "Recife - PE", categoria: "borracharia", whatsapp: "81987494998" },
{ nome: "Borracharia VIP", cidade: "Recife - PE", categoria: "borracharia", whatsapp: "8131276946" },
{ nome: "Casa do Borracheiro - Linha Pesada", cidade: "Recife - PE", categoria: "borracharia", whatsapp: "8138788271" },
{ nome: "Renove Pneus Truck Center", cidade: "Recife - PE", categoria: "borracharia", whatsapp: "81998740203" },
{ nome: "BORRACHARIA DO LORIM 24 HORAS", cidade: "Imperatriz - MA", categoria: "borracharia", whatsapp: "99992141315" },
{ nome: "LIMA PNEUS - Borracharia Móvel e Pesada", cidade: "Imperatriz - MA", categoria: "borracharia", whatsapp: "99984812339" },
{ nome: "Cardan Maranhão Truck Center", cidade: "São Luís - MA", categoria: "borracharia", whatsapp: "98992381014" },
{ nome: "Belcar Truck Center", cidade: "Santa Inês - MA", categoria: "borracharia", whatsapp: "98981872290" },
{ nome: "Belcar Truck Center", cidade: "Alto Alegre do Maranhão - MA", categoria: "borracharia", whatsapp: "99992193889" },
{ nome: "Top Carretas e Serviços", cidade: "Balsas - MA", categoria: "borracharia", whatsapp: "99988316441" },
{ nome: "Balança Mas Não Cai 24h", cidade: "São Luís - MA", categoria: "borracharia", whatsapp: "98981677471" },
{ nome: "Borracharia Emerson Bahia", cidade: "Imperatriz - MA", categoria: "borracharia", whatsapp: "99991994726" },
{ nome: "Borracharia Muniz 24h", cidade: "Imperatriz - MA", categoria: "borracharia", whatsapp: "99991223900" },
{ nome: "Borracharia HBS", cidade: "Imperatriz - MA", categoria: "borracharia", whatsapp: "99988238780" },
{ nome: "Borracharia Camboa", cidade: "São Luís - MA", categoria: "borracharia", whatsapp: "98984594257" },
];
{export function BrlistaDirectory() {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState<CategoryFilter>('Todas')
  const [currentPage, setCurrentPage] = useState(1)
  const searchInputRef = useRef<HTMLInputElement>(null)

  function formatPhoneForUrl(phone: string) {
    const digits = phone.replace(/\D/g, '')
    return digits.startsWith('55')? digits : `55${digits}`
  }
  function formatPhoneForDisplay(phone: string) {
    const d = phone.replace(/\D/g, '').replace(/^55/, '')
    if (d.length === 11) return `(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`
    if (d.length === 10) return `(${d.slice(0,2)}) ${d.slice(2,6)}-${d.slice(6)}`
    return phone
  }

  const normalize = (t: string) => t.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim()
  const getUf = (city: string) => (city.match(/,\s*([A-Z]{2})$/i) || city.match(/-\s*([A-Z]{2})$/i) || [])[1]?.toUpperCase() || ""
  const mapaEstados: any = {
    'ac':'AC','acre':'AC',
    'al':'AL','alagoas':'AL',
    'ap':'AP','amapa':'AP',
    'am':'AM','amazonas':'AM',
    'ba':'BA','bahia':'BA',
    'ce':'CE','ceara':'CE',
    'df':'DF','distrito federal':'DF','brasilia':'DF',
    'es':'ES','espirito santo':'ES',
    'go':'GO','goias':'GO',
    'ma':'MA','maranhao':'MA',
    'mt':'MT','mato grosso':'MT',
    'ms':'MS','mato grosso do sul':'MS',
    'mg':'MG','minas gerais':'MG','minas':'MG',
    'pa':'PA','para':'PA',
    'pb':'PB','paraiba':'PB',
    'pr':'PR','parana':'PR',
    'pe':'PE','pernambuco':'PE',
    'pi':'PI','piaui':'PI',
    'rj':'RJ','rio de janeiro':'RJ','rio':'RJ',
    'rn':'RN','rio grande do norte':'RN',
    'rs':'RS','rio grande do sul':'RS',
    'ro':'RO','rondonia':'RO',
    'rr':'RR','roraima':'RR',
    'sc':'SC','santa catarina':'SC',
    'sp':'SP','sao paulo':'SP',
    'se':'SE','sergipe':'SE',
    'to':'TO','tocantins':'TO'
  }

  const filteredPlaces = useMemo(() => {
    const q = normalize(query.trim())
    return places.filter((p) => {
      const ok = category === 'Todas' || p.category === category
      if (!q) return ok
      if (mapaEstados[q]) return ok && getUf(p.city) === mapaEstados[q]
      const txt = normalize(`${p.name} ${p.category} ${p.city} ${p.road?? ''} ${p.service?? ''}`)
      return ok && txt.includes(q)
    })
  }, [category, query])

  const itemsPerPage = 10
  const totalPages = Math.ceil(filteredPlaces.length / itemsPerPage)
  const paginatedPlaces = filteredPlaces.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage)
  const whatsappCadastro = `https://wa.me/5534988171945?text=${encodeURIComponent('Olá, quero cadastrar minha empresa/serviço no BRLista Brasil')}`

  return (
    <main className="min-h-screen bg-[#11110f] text-[#f6f4ed]">
      <header className="sticky top-0 z-20 border-b border-white/[0.08] bg-[#11110f]">
        <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-4">
          <div className="flex items-center gap-3">
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#facc15] text-black"><Wrench size={22}/></div>
            <div className="leading-none">
              <p className="text-[18px] font-black leading-none">BRLISTA</p>
              <p className="text-[18px] font-black leading-none text-[#facc15]">BRASIL</p>
              <p className="mt-1 text-[9px] tracking-[0.2em] text-white/50">SEU APOIO NA ESTRADA</p>
            </div>
          </div>
          <a href={whatsappCadastro} target="_blank" className="flex items-center gap-2 rounded-full bg-[#facc15] px-5 py-3 text-[11px] font-black leading-none text-black">
            <Plus size={14} /> Cadastrar<br/>Empresa
          </a>
        </div>
      </header>
      <div className="mx-auto max-w-6xl px-4 py-6">
        <div className="inline-flex items-center gap-2 rounded-full border border-[#facc15]/30 px-4 py-1.5 text-[10px] tracking-[0.2em] text-[#facc15]">
          <span className="h-2 w-2 rounded-full bg-[#facc15]"></span> GUIA DE SERVIÇOS RODOVIÁRIOS
        </div>
        <h1 className="mt-6 text-[44px] font-black leading-[0.9]">A estrada não<br/>espera.<br/><span className="text-[#facc15]">Encontre ajuda.</span></h1>
        <p className="mt-4 max-w-[360px] text-[14px] leading-relaxed text-white/60">Encontre borracharias, mecânicos, guinchos e socorro rodoviário 24h nas principais rodovias e cidades do Brasil.</p>
        <div className="relative mt-8">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#facc15]" size={18}/>
          <input ref={searchInputRef} value={query} enterKeyHint="search" onKeyDown={(e)=>{ if(e.key==='Enter'){ searchInputRef.current?.blur() }}} onChange={e=>{setQuery(e.target.value); setCurrentPage(1)}} placeholder="Buscar: rondonia, porto velho, vilhena, ariquemes..." className="w-full rounded-full border border-white/10 bg-white/[0.06] py-4 pl-12 pr-4 text-sm outline-none focus:border-[#facc15]/40" />
        </div>
        <p className="mt-10 text-[10px] tracking-[0.35em] text-[#facc15]">DIRETÓRIO DE APOIO • {filteredPlaces.length} LOCAIS</p>
        <div className="mt-4 flex flex-wrap gap-2">
          {categories.map(c=>(
            <button key={c} onClick={()=>{setCategory(c); setCurrentPage(1)}} className={`rounded-full px-4 py-2 text-xs font-bold border ${category===c?'bg-[#facc15] text-black border-[#facc15]':'bg-white/5 text-white/60 border-white/10'}`}>{c}</button>
          ))}
        </div>
        <div className="mt-6 grid gap-3 pb-10">
          {paginatedPlaces.map((p,i)=>(
            <div key={i} className="rounded-xl border border-white/[0.08] bg-white/[0.03] p-4">
              <div className="flex items-start justify-between">
                <div>
                  <h3 className="font-semibold">{p.name}</h3>
                  <p className="flex items-center gap-1 text-sm opacity-70"><MapPin size={12}/> {p.city} {p.road?`- ${p.road}`:''}</p>
                  <p className="mt-1 text-xs opacity-60">{p.category} {p.service?`- ${p.service}`:''}</p>
                </div>
                <a href={`https://wa.me/${formatPhoneForUrl(p.phone)}`} target="_blank" className="rounded-full bg-green-500 p-2"><MessageCircle size={18}/></a>
              </div>
              <div className="mt-3 flex gap-2">
                <a href={`tel:${formatPhoneForUrl(p.phone)}`} className="flex items-center gap-1 rounded-full bg-white px-3 py-1 text-sm text-black"><Phone size={14}/> {formatPhoneForDisplay(p.phone)}</a>
              </div>
            </div>
          ))}
        </div>
        {totalPages>1 && (
          <div className="mt-6 flex items-center justify-center gap-2 pb-10">
            <button disabled={currentPage===1} onClick={()=>setCurrentPage(c=>c-1)} className="rounded-full bg-white/[0.08] px-4 py-2 disabled:opacity-30">Anterior</button>
            <span className="text-sm opacity-60">{currentPage} / {totalPages}</span>
            <button disabled={currentPage===totalPages} onClick={()=>setCurrentPage(c=>c+1)} className="rounded-full bg-white/[0.08] px-4 py-2 disabled:opacity-30">Próximo</button>
          </div>
        )}
      </div>
    </main>
  )
}
